### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by szaghi** [cmacmackin/ford#1]
Dear cmacmackin, your project is very interesting. I am searching for documentation tool tailored to fortran with support to markdown output. However, the readme of ford is "reticent"... are there other docs? examples or tutorials?

My best regards

**Comment by cmacmackin** [comment]
Hi,
Yes, the documentation is, as yet, incomplete. (As, for that matter, is 
the version of ford which is currently on GitHub.) I hope to have better 
documentation available on GitHub by the end of today. At the moment I 
am still in the process of testing and debugging. It works for the sort 
of coding style I use, but I'm testing it out on a few other people's 
codes to see if they break it. As it happens, your OFF code is the one 
I'm testing it on right now. Once I've finished that I'll be writing the 
documentation. As I said, hopefully that will be available tonight. At 
worst it should be available by the end of the week.

I should warn you that the code will still be a work in progress and you 
may well get some run-time errors. In that case, please post a bug 
report to the GitHub page. While there is no guarantee that I'll get to 
debugging it in a timely manner (I'm busy with university and grad 
school applications) at the very least I'll have a list of things to 
sort out later when I have time.

Thanks for your interest!

On 04/01/15 04:24 PM, Stefano Zaghi wrote:
>
> Dear cmacmackin, your project is very interesting. I am searching for 
> documentation tool tailored to fortran with support to markdown 
> output. However, the readme of ford is "reticent"... are there other 
> docs? examples or tutorials?
>
> My best regards
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/1>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by szaghi** [comment]
Hi chris,
thank you for your replay. I will try your code the next week and I will
give you my feedbacks.

See you soon.

Il giorno 21:32 dom 04/gen/2015 Chris MacMackin <notifications@github.com>
ha scritto:

**Comment by cmacmackin** [comment]
Complete (or, at least, I think it's complete) documentation is now available in the README. If you have any questions which aren't explained there, don't hesitate to ask. However, I will be marking this issue as closed.
