### ISSUE TITLE
summary metadata: first-paragraph trigger has different behavior with respect summary marker

### ISSUE THREAD

**Issue by szaghi** [cmacmackin/ford#10]
Hi Chris,

I have noticed an apparently different behavior of *first paragraph* trigger with respect the *summary:* marker. 
Consider the following two images:
![no-summary](https://cloud.githubusercontent.com/assets/1661942/5683761/d66d6044-982a-11e4-9637-7061d45fd738.png)
![with-sum](https://cloud.githubusercontent.com/assets/1661942/5683760/d66a44e0-982a-11e4-8899-4f70dd8546e3.png)

In the first the summary is triggered by *summary:* marker, whereas in the second the marker is removed and the summary is triggered by the first paragraph. In both 2 ways the summary is correctly shown (see below), but only without *summary:* the summary is shown also into the description.
![summary](https://cloud.githubusercontent.com/assets/1661942/5683829/742450b8-982b-11e4-8af0-48c5aa68a721.png)

Is this a desired behavior or is it a bug?

**Comment by cmacmackin** [comment]
That was meant to be the desired behaviour. This idea was based off of the behaviour of the blogging software I use called Pelican. With Pelican, you can either specify a summary manually or let the software take the first hundred words or so of your article as the summary. The idea, then, is that by default the summary will just be the first little bit of your content, but if you want it to be something different then you can do that. The point of the default behaviour is _not_ just to let you avoid typing the summary tag, but rather the let you avoid writing a separate summary altogether. Make sense?

**Comment by szaghi** [comment]
Sure, it has sense. I just did not understand that immediately :-)

Consequently, for my "style" it is better to avoid the explicit marker: I
like the summary to be printed in both "list pages" (lists of procedures,
derived tupes, modules....) and the detailed description of each item,
right?

Thank you for the explanation.

Il giorno 19:39 ven 09/gen/2015 Chris MacMackin <notifications@github.com>
ha scritto:

**Comment by cmacmackin** [comment]
That's right.
