### ISSUE TITLE
Global switch to hide local variables

### ISSUE THREAD

**Issue by aradi** [cmacmackin/ford#100]
It would be nice to have a global switch to hide local variables. It would make it easy to use Ford for extracting the documentations of public API-s only, in the similar fashion as usually Doxygen is used.

**Comment by aradi** [comment]
What about having a `display: documented` setting (as a further option to all other `display` options), which only would

**Comment by aradi** [comment]
An alternative option would be to allow for a `display: documented` setting, which would only shows objects which has been documented.

**Comment by cmacmackin** [comment]
This has been on the todo list for some time. I'll try to get to it in 
the next few week or so.

On 16-05-09 09:05 PM, Bálint Aradi wrote:
>
> Reopened #100 <https://github.com/cmacmackin/ford/issues/100>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/100#event-654887073>
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>

**Comment by cmacmackin** [comment]
Implemented (finally). Default will still be to display procedure internals, though that might change with the next major release. I'm hoping to just get to a few more items on the todo list and then I'll make a release later today.
