### ISSUE TITLE
Crash with interfaces in program

### ISSUE THREAD

**Issue by jburgalat** [cmacmackin/ford#101]
Hi Chris,

There is a small bug when an interface is documented within a program unit.

Here is an example that produces such bug:

```fortran
PROGRAM bidon
  !! Create input dataset
  IMPLICIT NONE
  INTERFACE fun
    REAL(kind=8) FUNCTION a_function(vars)
      !! A function of _n_ arguments.
      REAL(kind=8), INTENT(in), DIMENSION(:) :: vars
        !! input arguments of the function
    END FUNCTION a_function
  END INTERFACE
END PROGRAM bidon
```

And here is the error raised:

Reading file src/bidon.f90

Processing documentation comments...
Correlating information from different parts of your project...

```
Traceback (most recent call last):
  File "/home/burgalat/.local/bin/ford", line 9, in <module>
    load_entry_point('FORD==4.5.0', 'console_scripts', 'ford')()
  File "/home/burgalat/code-projects/Python/contrib/ford/ford/__init__.py", line 312, in run
    main(proj_data,proj_docs,md)
  File "/home/burgalat/code-projects/Python/contrib/ford/ford/__init__.py", line 274, in main
    project.correlate()
  File "/home/burgalat/code-projects/Python/contrib/ford/ford/fortran_project.py", line 232, in correlate
    self.procedures.append(interfaces)
NameError: global name 'interfaces' is not defined
```

I checked the source code, it is a simple error about the iterated variable, `interfaces`, that should be set to `interface` in the loop at line 232.

**Comment by cmacmackin** [comment]
Huh, surprised that one hasn't surface before now. I'll fix it and put 
out a bugfix release tomorrow.

On 16-01-19 05:41 PM, Jérémie Burgalat wrote:
>
> Hi Chris,
>
> There is a small bug when an interface is documented within a program unit
>
> Here is an example that produces such bug:
>
> PROGRAM  bidon
>    !! Create input dataset
>    IMPLICIT NONE
>    INTERFACE  fun
>      REAL(kind=8) FUNCTION a_function(vars)
>        !! A function of _n_ arguments
>        REAL(kind=8),INTENT(in),DIMENSION(:)::  vars
>          !! input arguments of the function
>      END  FUNCTION  a_function
>    END INTERFACE
> END PROGRAM  bidon
>
> And here is the error raised:
>
> Reading file src/bidonf90
>
> Processing documentation comments
> Correlating information from different parts of your project
>
> |Traceback (most recent call last): File 
> "/home/burgalat/local/bin/ford", line 9, in <module> 
> load_entry_point('FORD==450', 'console_scripts', 'ford')() File 
> "/home/burgalat/code-projects/Python/contrib/ford/ford/__init__py", 
> line 312, in run main(proj_data,proj_docs,md) File 
> "/home/burgalat/code-projects/Python/contrib/ford/ford/__init__py", 
> line 274, in main projectcorrelate() File 
> "/home/burgalat/code-projects/Python/contrib/ford/ford/fortran_projectpy", 
> line 232, in correlate selfproceduresappend(interfaces) NameError: 
> global name 'interfaces' is not defined |
>
> I checked the source code, it is a simple error about the iterated 
> variable, |interfaces|, that should be set to |interface| in the loop 
> at line 232
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/101>.
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>

**Comment by cmacmackin** [comment]
Fixed it. Sorry for the slight delay.
