### ISSUE TITLE
gitter.im sidecar support

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#102]
Hi Chris,
I've done some experimenting, and it seems that you can simply drop in the [sidecar](https://sidecar.gitter.im) generated `<script>...</script>` tags into the projects main project file (making sure that there's no indentation, so that the code isn't rendered as code, but interpreted as embedded html instead. There is one problem though: The top navbar is always on-top so the top of the gitter.im sidecar chat box ends up rendering behind the FORD top navigation bar.

So, I'm wondering, in the mean time do you know of a way, such as specifying a different `targetElement`, to get the top of the chat to not render underneath the top navbar? Or some css that I can apply to get the chat to stay on top?

In the longer run, I'm curious if you would consider adding sidecar as an option that can be enabled in the FORD project file. It would be nice (although perhaps not possible) if  you could navigate around in the documentation without affecting the state of the gitter.im sidecar chat window.

**Comment by cmacmackin** [comment]
I definitely have a look at the CSS to see what can be done. Adding 
sidecar as an option to FORD should be completely doable. I don't know 
enough about how sidecar works to be able to say if there is a way to 
allow you to navigate around the documentation without affecting 
sidecar, though.

On 20/01/16 22:35, Izaak Beekman wrote:
>
> Hi Chris,
> I've done some experimenting, and it seems that you can simply drop in 
> the sidecar <https://sidecar.gitter.im> generated 
> |<script>...</script>| tags into the projects main project file 
> (making sure that there's no indentation, so that the code isn't 
> rendered as code, but interpreted as embedded html instead. There is 
> one problem though: The top navbar is always on-top so the top of the 
> gitter.im sidecar chat box ends up rendering behind the FORD top 
> navigation bar.
>
> So, I'm wondering, in the mean time do you know of a way, such as 
> specifying a different |targetElement|, to get the top of the chat to 
> not render underneath the top navbar? Or some css that I can apply to 
> get the chat to stay on top?
>
> In the longer run, I'm curious if you would consider adding sidecar as 
> an option that can be enabled in the FORD project file. It would be 
> nice (although perhaps not possible) if you could navigate around in 
> the documentation without affecting the state of the gitter.im sidecar 
> chat window.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/102>.
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>

**Comment by zbeekman** [comment]
yup, the latter request may not be feasible. You rock Chris!

BTW, i have a question that has more to do with the python markdown engine than FORD, but I was wondering if you knew the answer:

I like to use the extension `markdown.extensions.toc` and have been trying to figure out a way to use a `marker` (other than the default, `[TOC]`, so that the TOC gets processed when running FORD, but the [TOC] marker stays hidden, say when looking at the project file on github.com. Do you have any ideas on how I might be able to accomplish that? It may not be doable. I've experimented with markdown comments ( `[i'm a comment]: # (I think this is too! we're using repurposed links)`) and HTML comments but it seems that these end up getting stripped out before the TOC processing occurs, so the TOC is never inserted.

**Comment by cmacmackin** [comment]
If that doesn't work then I'm guessing it's impossible. Looking at the TOC extension [source code](https://github.com/waylan/Python-Markdown/blob/master/markdown/extensions/toc.py#L126), I see that it's implemented using a TreeProcessor, and these are among the last things to be applied when the Markdown is being processed. Unfortunately, that probably means that any tricks like the ones you've tried won't work. Using HTML comments won't work because, by default, Markdown does not process anything within HTML tags. Even if it did, the table of contents would still be in a comment in the HTML output, so it wouldn't show up in the documentation.

I'm not 100% clear what your use case is. Would it be possible to have the project file contents, except the metadata and [TOC] tag, in a separate file which would then be imported into the project file using my [markdown-include](https://github.com/cmacmackin/markdown-include) plugin?

**Comment by zbeekman** [comment]
yes certainly, using markdown-include is an option...

I figured the TOC was probably processed late, and thats why my tricks were failing.

My use case is just to make project files more readable on github. Not because any consumer of the project would want to browse the project file there, but because people who hack on the code might want to take a glance.... See https://github.com/zbeekman/json-fortran/blob/md-cleanup/json-fortran.md (will delete branch once merged, so this link may stop working)

The biggest recommendation I have so far, on this front, is to use the YAML style metadata fences:

`---` on the very first line of the document, and then `---` on the line immediately after meta data ends. This causes it to be rendered much more clearly on github.

**Comment by cmacmackin** [comment]
Does the metadata will get picked up properly if you do that?

On 21/01/16 15:24, Izaak Beekman wrote:
>
> yes certainly, using markdown-include is an option...
>
> I figured the TOC was probably processed late, and thats why my tricks 
> were failing.
>
> My use case is just to make project files more readable on github. Not 
> because any consumer of the project would want to browse the project 
> file there, but because people who hack on the code might want to take 
> a glance.... See 
> https://github.com/zbeekman/json-fortran/blob/md-cleanup/json-fortran.md 
> (will delete branch once merged, so this link may stop working)
>
> The biggest recommendation I have so far, on this front, is to use the 
> YAML style metadata fences:
>
> |---| on the very first line of the document, and then |---| on the 
> line immediately after meta data ends. This causes it to be rendered 
> much more clearly on github.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/102#issuecomment-173604922>.
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>

**Comment by zbeekman** [comment]
yes, it certainly does. Depending on the markdown engine, that YAML style metadata is fairly common. I did some research and the python markdown engine will still correctly parse the metadata

**Comment by szaghi** [comment]
Not sure I am on topic (I have not completely followed the above posts), but I am using [Python yaml](https://github.com/szaghi/MaTiSSe/blob/master/src/main/python/matisse/theme.py#L9) to parse metadata into markdown sources.

**Comment by zbeekman** [comment]
@szaghi the discussion turned away from my original question about integrating http://sidecar.gitter.im into FORD and turned to discussing things I can do to clean up the rendering of the FORD project file when displayed on github. I have found that FORD will process the meta data section if you include the

```md
---
metadata1: stuff
metadata2: morestuff
---
```

`---` lines as the first line of the document and as the line immediately following the end of the metadata. This causes github.com to render the metadata in a table, instead of a jumbled paragraph.

Take a look at the "rich diff" of my PR for json-fortran: https://github.com/jacobwilliams/json-fortran/pull/169/files?short_path=97b64d9#diff-97b64d9ab430bcd8f7f846007be6dd91

**Comment by szaghi** [comment]
@zbeekman ah, ok, sorry for my OT

**Comment by cmacmackin** [comment]
I've added builtin support for sidecar to Ford, including ensuring that it will show up above the navigation bar. However, I don't see any way that you can keep it open as you navigate around the documentation. Perhaps if I knew more JavaScript I could find a way, but I'm quite weak on that front.

**Comment by zbeekman** [comment]
Chris, you are a rock star! Thanks so much for adding this!
