### ISSUE TITLE
Fails if subroutine signature has whitespace but no parameters

### ISSUE THREAD

**Issue by jonekoo** [cmacmackin/ford#106]
Hello,

First of all, thank you for creating and maintaining FORD. It is great!

I think I found a minor bug in subroutine argument parsing which can be reduced to the following:
If I run a file containing

```
subroutine do_nothing( )
end subroutine do_nothing
```

through FORD 4.5.1 it produces

_Reading file noargs.f90
Warning: Error parsing noargs.f90.
	string index out of range
Error: No source files with appropriate extension found in specified directory._

Here are the files needed to reproduce:
[noargs_whitespace_bug.zip](https://github.com/cmacmackin/ford/files/124813/noargs_whitespace_bug.zip)

If one removes the whitespace between the parenthesis in the subroutine signature, the problem disappears.

BR, Jouni

P.S. Sorry for any noobishness. I'm just learning how to participate in GitHub.

**Comment by cmacmackin** [comment]
Thanks for the tip. No need to worry about any inexperience; you're bug report had all of the information necessary. In particular, thanks for coming up with a minimal example. This should be quick to fix, but seeing as it isn't a catastrophic one (you can always just remove the whitespace) I'll probably wait until I get around to developing the next release. I can't promise when this will be, as I'm focusing more on another project at the moment, though.

**Comment by cmacmackin** [comment]
Fixed in  [v4.5.2](https://github.com/cmacmackin/ford/releases/tag/v4.5.2). Can be installed with `pip install --upgrade ford`.

**Comment by aadeeGirl** [comment]
Hello,

I am recently learning to use FORD, but seem to be stuck with a similar error. 

Error: No source files with appropriate extension found in specified directory.

I am trying to document a project, and have lots of .f90 files, but keep running into this error. In addition I tried the noargs_whitespace_bug attachment in the issue #106 above, and still had the same error.
Any help with fixing this would be greatly appreciated.
I have Ford 5.0.6, installed with homebrew.

Adura.
