### ISSUE TITLE
no comments for arguments of type-bound procedures

### ISSUE THREAD

**Issue by jdonners** [cmacmackin/ford#108]
Hi,

thanks for a wonderful tool.

I noticed that arguments of public subroutines are commented in the resulting documentation, but the arguments of type-bound procedures are not. Can that be changed?

**Comment by szaghi** [comment]
Hi @jdonners can you elaborate more?

I my usage of the wonderful FORD all arguments *documented* of all procedures are *commented*, TBP included, e.g. see [this](http://fortran-foss-programmers.github.io/FOODIE/type/euler_1d_caf.html#boundprocedure-dt%7E2): *self, Nmax, Tmax, t and CFL* are all *documented*.

I do not understand what you mean with *commented in the resulting documentation*.

See you soon.

**Comment by jdonners** [comment]
hmm, I must've been half-asleep when I wrote this issue.. Indeed it works as might be expected.
