### ISSUE TITLE
Crashes if first line of doc contains a colon

### ISSUE THREAD

**Issue by cmacmackin** [cmacmackin/ford#11]
FORD will crash if it encounters a one-line documentation comment containing a colon. That is because it is interpreting it as metadata and then can't seem to handle the syntax (the fact that there are multiple words before the colon, perhaps). Not 100% certain what causes the crash, but that's besides the point. There needs to be some way for people to make it clear that the first line of their documentation does not contain any metadata.

**Comment by cmacmackin** [comment]
Fixed this. FORD will check if a doc could cause these problems sending it to Markdown. It will insert lines above and below, as appropriate. Fix will be sent to Github in the next push.

**Comment by szaghi** [comment]
Great!

Il giorno 03:49 sab 17/gen/2015 Chris MacMackin <notifications@github.com>
ha scritto:
