### ISSUE TITLE
Function argument causes crash

### ISSUE THREAD

**Issue by rhdtownsend** [cmacmackin/ford#110]
When running FORD on the module below, I get a crash following backtrace:

Reading file mymod.f90
Traceback (most recent call last):
  File "/Users/townsend/anaconda/bin/ford", line 11, in <module>
    sys.exit(run())
  File "/Users/townsend/anaconda/lib/python3.5/site-packages/ford/__init__.py", line 312, in run
    main(proj_data,proj_docs,md)
  File "/Users/townsend/anaconda/lib/python3.5/site-packages/ford/__init__.py", line 264, in main
    project = ford.fortran_project.Project(proj_data)
  File "/Users/townsend/anaconda/lib/python3.5/site-packages/ford/fortran_project.py", line 90, in __init__
    self.files.append(ford.sourceform.FortranSourceFile(os.path.join(curdir,item),settings,fpp))
  File "/Users/townsend/anaconda/lib/python3.5/site-packages/ford/sourceform.py", line 919, in __init__
    FortranContainer.__init__(self,source,"")
  File "/Users/townsend/anaconda/lib/python3.5/site-packages/ford/sourceform.py", line 581, in __init__
    self.MODULE_RE.match(line),self))
  File "/Users/townsend/anaconda/lib/python3.5/site-packages/ford/sourceform.py", line 611, in __init__
    permission))
  File "/Users/townsend/anaconda/lib/python3.5/site-packages/ford/sourceform.py", line 562, in __init__
    self._cleanup()
  File "/Users/townsend/anaconda/lib/python3.5/site-packages/ford/sourceform.py", line 1268, in _cleanup
    for proc in intr.subroutines + intr.functions:
AttributeError: 'FortranInterface' object has no attribute 'subroutines'

The problem appears to be with the func function argument.

Other than this, FORD appears to work great with my project; thanks for creating such a useful piece of software.

cheers,

Rich

`
module mymod

  ! No implicit typing

  implicit none

  ! Procedures

contains

  function myfunc (func)

    interface
       function func (x)
         real, intent(in) :: x
         real             :: func
       end function func
    end interface
    real :: myfunc

  end function myfunc

end module mymod`

**Comment by zbeekman** [comment]
I haven't checked the standard yet, but I'm not convinced this is valid Fortran >= 95. My concern is the function declarations both contained in the module and contained in the interface block within the function. Don't you need to either declare:

```
real function func (x)
...
```

or

```
function func (x) result(res)
```

Appologies in advance if I am mistaken... I'll try to look this up if I find more time.

**Comment by rhdtownsend** [comment]
> On Feb 19, 2016, at 11:50 AM, Izaak Beekman <notifications@github.com> wrote:
> 
> I haven't checked the standard yet, but I'm not convinced this is valid Fortran >= 95. My concern is the function declarations both contained in the module and contained in the interface block within the function. Don't you need to either declare:
> 
> real function func (x)
> ...
> 
> or
> 
> function func (x) result(res)
> 
> Appologies in advance if I am mistaken... I'll try to look this up if I find more time.
> 
> —

No, this is perfectly valid. The type of the function is declared in the body:

       function func (x)
         real, intent(in) :: x
         real             :: func   <— here

(Or maybe I’m not understanding your comment correctly).

cheers,

Rich

**Comment by zbeekman** [comment]
After taking a look at [the standard](ftp://ftp.nag.co.uk/sc22wg5/N1751-N1800/N1791.pdf), I'm still not entirely convinced that your usage is *technically* legal Fortran and not a compiler extension. I'm not arguing with you as to whether or not it will work with the majority of compilers. I'm not saying that FORD should or should not support such usage. I'm not even saying that my understanding of the standard is correct! Section 12.6.2.2 "Function subprogram", paragraph 3, page 307:

> The type and type parameters (if any) of the result of the function defined by a function subprogram may be specified by a type specification in the FUNCTION statement or by the name of the result variable appearing in a type declaration statement in the specification part of the function subprogram. They shall not be specified both ways. If they are not specified either way, they are determined by the implicit typing rules in effect within the function subprogram. If the function result is an array, allocatable, or a pointer, this shall be specified by specifications of the name of the result variable within the function body. The specifications of the function result attributes, the specification of dummy argument attributes, and the information in the procedure heading collectively define the characteristics of the function (12.3.1).

Despite the standards ambiguity here, to me it sounds like you can do either: `real function foo(args)` *or* `function foo(args) result(res) ; real :: res`. I am not asserting my understanding is correct, however.

FWIW, GFortran doesn't have an issue with your usage, even when extra, all, standard and pedantic warnings are turned on. Stylistically I certainly don't like it. Is it *technically* legal Fortran? I don't know.

**Comment by rhdtownsend** [comment]
> On Feb 19, 2016, at 1:42 PM, Izaak Beekman <notifications@github.com> wrote:
> 
> After taking a look at the standard, I'm still not entirely convinced that your usage is technically legal Fortran and not a compiler extension. I'm not arguing with you as to whether or not it will work with the majority of compilers. I'm not saying that FORD should or should not support such usage. I'm not even saying that my understanding of the standard is correct! Section 12.6.2.2 "Function subprogram", paragraph 3, page 307:
> 
> The type and type parameters (if any) of the result of the function defined by a function subprogram may be specified by a type specification in the FUNCTION statement or by the name of the result variable appearing in a type declaration statement in the specification part of the function subprogram. They shall not be specified both ways. If they are not specified either way, they are determined by the implicit typing rules in effect within the function subprogram. If the function result is an array, allocatable, or a pointer, this shall be specified by specifications of the name of the result variable within the function body. The specifications of the function result attributes, the specification of dummy argument attributes, and the information in the procedure heading collectively define the characteristics of the function (12.3.1).
> 
> Despite the standards ambiguity here, to me it sounds like you can do either: real function foo(args) or function foo(args) result(res) ; real :: res. I am not asserting my understanding is correct, however.
> 

There are two separate issues here: how the name of the function result variable is determined, and how the type of the result variable is determined.

The text you quote above from the F2008 standard concerns the second issue: how the type of the result variable is determined. Paragraph 4 of the same section discusses how the result variable name is determined:

"If RESULT appears, the name of the result variable of the function is result-name and all occurrences of the function name in execution-part statements in its scope refer to the function itself. If RESULT does not appear, the name of the
result variable is function-name and all occurrences of the function name in execution-part statements in its scope are references to the result variable."


> FWIW, GFortran doesn't have an issue with your usage, even when extra, all, standard and pedantic warnings are turned on. Stylistically I certainly don't like it. Is it technically legal Fortran? I don't know.
> 

Yes, it is perfectly legal. Just look at the example code given in note 12.42:

RECURSIVE FUNCTION CUMM_SUM (ARRAY) RESULT (C_SUM)
  REAL, INTENT (IN), DIMENSION (:) :: ARRAY
  REAL, DIMENSION(SIZE (ARRAY)) ::C_SUM

Ignoring the RECURSIVE attribute (because it’s incidental to our discussion), here’s an example of a function with (i) the result variable name defined using a RESULT() clause, and (ii) the result variable type defined by a type declaration statement in the specification part of the statement.

cheers,

Rich

**Comment by zbeekman** [comment]
As I said above and I'll say again, you may certainly be right, on all accounts. :smile: 

> Yes, it is perfectly legal. Just look at the example code given in note 12.42:
> 
> RECURSIVE FUNCTION CUMM_SUM (ARRAY) RESULT (C_SUM)
>   REAL, INTENT (IN), DIMENSION (:) :: ARRAY
>   REAL, DIMENSION(SIZE (ARRAY)) ::C_SUM
> 
> Ignoring the RECURSIVE attribute (because it’s incidental to our discussion), here’s an example of a function with (i) the result variable name defined using a RESULT() clause, and (ii) the result variable type defined by a type declaration statement in the specification part of the statement.

The difference I see is that the example code from the standard has *BOTH* a result clause, *and* result variable declaration. Your code has *only* the result/function variable declaration.

In the end, I suspect you're right and that it is legal. C1253 (same section) seems to imply this:

> C1253 (R1228) If RESULT appears, the function-name shall not appear in any specification statement in the scoping unit of the function subprogram.

(This implies that if RESULT does not appear, function-name may appear in a specification statement in the scoping unit of the function subprogram.)

Always interesting trying to make sense of the standard. I appreciate the discussion.

**Comment by rhdtownsend** [comment]
> On Feb 19, 2016, at 2:32 PM, Izaak Beekman <notifications@github.com> wrote:
> 
> As I said above and I'll say again, you may certainly be right, on all accounts. 
> 
> Yes, it is perfectly legal. Just look at the example code given in note 12.42:
> 
> RECURSIVE FUNCTION CUMM_SUM (ARRAY) RESULT (C_SUM)
> REAL, INTENT (IN), DIMENSION (:) :: ARRAY
> REAL, DIMENSION(SIZE (ARRAY)) ::C_SUM
> 
> Ignoring the RECURSIVE attribute (because it’s incidental to our discussion), here’s an example of a function with (i) the result variable name defined using a RESULT() clause, and (ii) the result variable type defined by a type declaration statement in the specification part of the statement.
> 
> The difference I see is that the example code from the standard has BOTH a result clause, and result variable declaration. Your code has only the result/function variable declaration.
> 

Ah, I should have gone back and read my own code — you’re right, I don’t have a result clause. 

So, as per paragraph 4 ("If RESULT does not appear, the name of the result variable is function-name”), the name of the result variable is taken from the name ‘func’ of the function; and then, as per paragraph 3 ("by the name of the result variable appearing in a type declaration statement”), the type of the result variable is taken from the type declaration for ‘func’.

> In the end, I suspect you're right and that it is legal. C1253 (same section) seems to imply this:
> 
> C1253 (R1228) If RESULT appears, the function-name shall not appear in any specification statement in the scoping unit of the function subprogram.
> 
> (This implies that if RESULT does not appear, function-name may appear in a specification statement in the scoping unit of the function subprogram.)
> 
> Always interesting trying to make sense of the standard. I appreciate the discussion.

My pleasure — I’m always happy to help those who are helping me (by maintaining FORD)!

cheers,

Rich

**Comment by rhdtownsend** [comment]
As an addendum: the form

      function func (x)
        real x
        real func

…is the *only* way to declare a function in Fortran 77 (result clauses, plus in-line type declarations, are F9x). 

cheers,

Rich

**Comment by zbeekman** [comment]
> My pleasure — I’m always happy to help those who are helping me (by maintaining FORD)!

I contribute to FORD sometimes, but I'm not sure I'd call myself a maintainer. @cmacmackin does all the heavy lifting

> …is the *only* way to declare a function in Fortran 77 (result clauses, plus in-line type declarations, are F9x).

Oh, I see. Just FYI Fortran 77 is explicitly *NOT* supported by FORD.

**Comment by rhdtownsend** [comment]
> On Feb 19, 2016, at 3:20 PM, Izaak Beekman <notifications@github.com> wrote:
> 
> My pleasure — I’m always happy to help those who are helping me (by maintaining FORD)!
> 
> I contribute to FORD sometimes, but I'm not sure I'd call myself a maintainer. @cmacmackin does all the heavy lifting
> 
> …is the only way to declare a function in Fortran 77 (result clauses, plus in-line type declarations, are F9x).
> 
> Oh, I see. Just FYI Fortran 77 is explicitly NOT supported by FORD.

OK, understood. By ‘Fortran 77’, I think you mean fixed-format F77, since all valid F77 is also valid F9x.

My point was that because my function declaration was valid F77 (if the intent statements are removed, and if converted to fixed format), then it must be valid F9x.

cheers,

Rich

**Comment by cmacmackin** [comment]
I should probably actually contribute to this discussion at some point... 

As far as I know, the original code snippet is standards-conforming. Given that Fortran strives to be backwards compatible, I don't think the standard would intentionally make such FORTRAN77 syntax illegal. I certainly have built FORD to be able to handle that technique of declaring a function type. The only F77 things which FORD doesn't support now is fixed-format code (although if anyone ever wrote me a method to convert fixed-format to free-format then I'd be happy to include it), common blocks (they go undocumented) and the `data` statement (FORD is unaware that the variables are initialized).

In any case, I've been dealing with various bug reports recently and am just digging through the code now to track down the problem here. When I wrote FORD I did specifically test it with that sort of example, so I must have introduced a regression at some point.

**Comment by zbeekman** [comment]
If it is indeed a regression, give git bisect a try; it will help you
determine the changes that introduced the issue, thereby decreasing the
amount of code you have to search.

**Comment by cmacmackin** [comment]
Found it (without need to use bisection in the end). I'm pretty sure this regression got introduced quite early on in FORD's lifespan, so I'm amazed no one has caught it until now! Anyway, there are a few more bug reports I want to get through and then I'll push out a new release--hopefully by the end of the weekend.

**Comment by cmacmackin** [comment]
I should also warn you that you might want to run FORD with the flag `--no-search` while you're playing with it. For large projects (and this one is pretty massive) it will take a _very_ long time to index the documentation for searching (10s of minutes to hours). This can be sped up somewhat if [lxml](http://lxml.de/) is installed, but even when it was I found the wait intolerable.

**Comment by cmacmackin** [comment]
Fixed in  [v4.5.2](https://github.com/cmacmackin/ford/releases/tag/v4.5.2). Can be installed with `pip install --upgrade ford`.
