### ISSUE TITLE
Syntax highlighting of error stop statement

### ISSUE THREAD

**Issue by deber** [cmacmackin/ford#112]
In the Fortran 2008 statement "error stop", only "stop" is highlighted.

**Comment by cmacmackin** [comment]
This is an upstream problem with the [Pygments](http://pygments.org/) package used for syntax highlighting. I'll lodge a bug report (and maybe a pull request) with them.

**Comment by cmacmackin** [comment]
I lodged a bug report with them months ago. Unfortunately, as far as I know, it still hasn't been fixed. In any case, this isn't a problem with FORD itself, so I'm going to close this issue.
