### ISSUE TITLE
coloured edges: 

### ISSUE THREAD

**Issue by StephenJTurnbull** [cmacmackin/ford#113]
I used FORD on a ... very... large program with a large number of files and classes. 

The resulting image was somewhat difficult to read because of so many overlapping dashed lines between classes. 

So I made two small changes to graphs.py 
******************************Line 40ish**************************************
import colorsys
def rainbowcolour(depth, maxd):
   (r, g, b) = colorsys.hsv_to_rgb(float(depth) / maxd, 1.0, 1.0)
   R, G, B = int(255 * r), int(255 * g), int(255 * b)
   return R, G, B
******************************Line 425ish:************************************
class UsesGraph(FortranGraph):
    def add_more_nodes(self,nodes):
        """
        Adds nodes for the modules used by those listed in nodes. Adds
        edges between them. Also does this for ancestor (sub)modules.
        """
        for i,n in zip(range(len(nodes)),nodes):
            r,g,b = rainbowcolour(i,len(nodes))
            colour = '#%02X%02X%02X' % (r,g,b)
            self.add_node([x for x in n.uses if x.ident not in self.added])
            for nu in n.uses:
                self.dot.edge(nu.ident,n.ident,style='dashed',color = colour)
            if hasattr(n,'ancestor'):
                if n.ancestor.ident not in self.added: self.add_node([n.ancestor])
                self.dot.edge(n.ancestor.ident,n.ident)
********************************************************************************

Now every line has a bold easy to see colour (with a few exceptions) which depends on the node that it points to.   

It's not perfect and for very high number of nodes the colours are not all unique. but you might want to implement something similar.

**Comment by StephenJTurnbull** [comment]
The final result: 
![maggie](https://cloud.githubusercontent.com/assets/11338397/13441883/9adc2390-dfc7-11e5-9876-b43d3b6e4084.png)

**Comment by cmacmackin** [comment]
This looks like an interesting feature. Could you produce a diff file for your changes? I think I'll add it to the next release as an option.

**Comment by zbeekman** [comment]
I think that's pretty handy, and looks great!

**Comment by StephenJTurnbull** [comment]
[graphchanges.txt](https://github.com/cmacmackin/ford/files/155394/graphchanges.txt)

The attached is a simple diff from Git. highlighting the 9 lines changed off the SPOOF branch

**Comment by cmacmackin** [comment]
Added this feature. Will be in the next release.

**Comment by lstagner** [comment]
Could you make this an option? I am not a fan of this change.

**Comment by cmacmackin** [comment]
This feature will now have to be explicitely turned on using `coloured_edges: true` in the project file. Sorry to any Americans who don't know the correct way to spell that ;)

**Comment by szaghi** [comment]
Also Italians have problems with spellllllliiiinnnnngggg :smile:
