### ISSUE TITLE
Add possibility to link to other documentation chapters

### ISSUE THREAD

**Issue by p-vitt** [cmacmackin/ford#114]
I'm writing a rather longish documentaion on some data structures in a markdown file. As the data structures share a more or less common interface, and also the behavior is one some parts very similar, I want to link from one chapter to another chapter. Example:

    ## Par1
    some text here

    ## Par2
    See Par1

My first idea was to write it like

    See [Par1]

but the documentation on links says:

 > It could be a procedure, module, or anything else with its own page of documentation.

As the first paragraph is neither fortran code nor has it it's own page, I fear the Ford links don't work for this use case. My next idea was to use relative html links to link to the heading like you can do in e.g. [Wikipedia](https://en.wikipedia.org/wiki/Wikipedia#History) (here I link to the history chapter). But this also won't work as Ford doesn't set the id tag on headings.

Is there any way to achieve what I want to do? Or is there something planned? If not, I propose to at least add the id tag into html.

**Comment by cmacmackin** [comment]
You'll be wanting to use the [TOC plugin](http://pythonhosted.org/Markdown/extensions/toc.html) for Markdown. To do this, just add
```
md_extensions: markdown.extensions.toc
```
to the metadata in your project file. It will then provide IDs for each header. You don't need to actually print the table of contents if you don't want to--it will only be printed in places you write `[TOC]`--but you'll still get the IDs.

**Comment by p-vitt** [comment]
Thanks for the extremly fast reply. I wasn't aware of this being a markdown feature.
