### ISSUE TITLE
Include syntax conflicts with LaTeX

### ISSUE THREAD

**Issue by cmacmackin** [cmacmackin/ford#12]
The {{filename}} syntax of my Markdown-Include extension isn't quite as error-proof as I'd hoped. Occasionally, in LaTeX equations or in code fragments, people will use a {{ and a }} somewhere, which causes an incorrect error-message to be printed and that text to be removed. Will probably need to come up with some new syntax.

**Comment by szaghi** [comment]
Interesting.

I don't know how to find a safe syntax... I think that trial and error is your way. What about *[[other_file.md]]*? It is the syntax to link (note link, not include) external md into wiki pages.

**Comment by cmacmackin** [comment]
I've settled on the syntax ``{!filename!}`` for the include feature. I don't think that there is anything which is likely to conflict with this. I'd prefer to avoid the use square brackets, as they are used for a few things in Markdown already. I'd also be wary of someone using some plugin to reproduce the Github wiki link syntax.

**Comment by szaghi** [comment]
Perfect. I will change my sources to be compliant with this new syntax.

Il giorno 04:39 sab 17/gen/2015 Chris MacMackin <notifications@github.com>
ha scritto:
