### ISSUE TITLE
Regex for USE statements inconsistent with standards

### ISSUE THREAD

**Issue by sliska314** [cmacmackin/ford#120]
Hi, FORD does not recognized modules that are USEd with the syntax:
use :: module-name

In Fortran 2003 and 2008 USE statements are of the form:
USE [ [ , module-nature ] :: ] module-name ...

I think the regex for USE statements in sourceform.py needs to be updated from:
`USE_RE = re.compile("^use(?:\s*,\s*(?:non_)?intrinsic\s*::\s*|\s+)(\w+)\s*($|,.*)", ...`

to something like:
`USE_RE =  re.compile("^use(?:\s*,\s*(?:non_)?intrinsic\s*::\s*|\s*::\s*|\s+)(\w+)\s*($|,.*)", ...`

**Comment by szaghi** [comment]
In FoBiS I use this https://github.com/szaghi/FoBiS/blob/master/src/main/python/fobis/ParsedFile.py#L115

Not sure if this regex is more robust. I capture separately some other intrinsic modules (iso_c, fortran_env, etc...) 
https://github.com/szaghi/FoBiS/blob/master/src/main/python/fobis/ParsedFile.py#L121
https://github.com/szaghi/FoBiS/blob/master/src/main/python/fobis/ParsedFile.py#L125

**Comment by zbeekman** [comment]
I agree that this is legal and should be supported... Maybe someone (possibly me?) can work up a PR for Chris?

**Comment by cmacmackin** [comment]
Sorry I haven't been responding. I've been focusing on some programming 
I have to do for my research and haven't gotten around to dealing with 
FORD. I agree that this should be legal and would be happy to accept a 
pull request.

On 04/04/16 00:56, Izaak Beekman wrote:
>
> I agree that this is legal and should be supported... Maybe someone 
> (possibly me?) can work up a PR for Chris?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/120#issuecomment-205079499>
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>

**Comment by cmacmackin** [comment]
Fixed with #123
