### ISSUE TITLE
Ordering of Pages

### ISSUE THREAD

**Issue by lstagner** [cmacmackin/ford#121]
Is there a way to change the ordering of the pages
![screenshot from 2016-04-03 23-27-33](https://cloud.githubusercontent.com/assets/4305891/14239728/c0716958-f9f3-11e5-8914-d37730c67852.png)

I want to change the order of the pages so they go in a logical order

**Comment by cmacmackin** [comment]
No, there isn't a way to do this, which was a bad oversight on my part. 
I'll try to add some sort of feature along these lines for the next release.

On 04/04/16 07:29, Luke Stagner wrote:
>
> Is there a way to change the ordering of the pages
> screenshot from 2016-04-03 23-27-33 
> <https://cloud.githubusercontent.com/assets/4305891/14239728/c0716958-f9f3-11e5-8914-d37730c67852.png>
>
> I want to change the order of the pages so they go in a logical order
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/121>
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>

**Comment by lstagner** [comment]
What determines the order?

BTW http://d3denergetic.github.io/FIDASIM/ so thanks

**Comment by cmacmackin** [comment]
The order is that returned by the `os.listdir()` method in Python which, according to its documentation, is arbitrary. Sorry.

**Comment by lstagner** [comment]
As a stop gap you could just sort the list. Some order is better than nothing
