### ISSUE TITLE
Linking to source files

### ISSUE THREAD

**Issue by lstagner** [cmacmackin/ford#124]
In project I am working on we have a lot of non-fortran files. Each file corresponds with a function or procedure. While I can link to the source file using standard markdown linking eg `[source_file](|url|/source_file.pro)` It would be nice to be able to use the short form linking `[[source_file.pro]]`

**Comment by cmacmackin** [comment]
Shouldn't be hard to do. I'll put it in the next release.

On 08/04/16 08:27, Luke Stagner wrote:
>
> In project I am working on we have a lot of non-fortran files. Each 
> file corresponds with a function or procedure. While I can link to the 
> source file using standard markdown linking eg 
> |[source_file](|url|/source_file.pro)| It would be nice to be able to 
> use the short form linking |[[source_file.pro]]|
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/124>
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>

**Comment by cmacmackin** [comment]
I'm not quite clear on what you're trying to do here. Are these non-Fortran files ones specified with the [extra_filetypes](https://github.com/cmacmackin/ford/wiki/Project-File-Options#extra_filetypes) option? If so, then the short form linking should already work for them. I'm not clear on what sort of file you could access with `[source_file](|url|/source_file.pro)`, as no user-supplied files are placed in the top directory of the output.

**Comment by lstagner** [comment]
I would just like to use [[sourcefile.pro]] to add a link instead of [sourcefile.pro](|url|/sourcefile/sourcefile.pro)

**Comment by cmacmackin** [comment]
Yes, I realize that, but what is `sourcefile.pro`? FORD has to recognize it in some way for it to end up in the documentation output. It might see it as a non-Fortran source file whose suffix has been specified in the [extra_filetypes](https://github.com/cmacmackin/ford/wiki/Project-File-Options#extra_filetypes) option
in the project file. Perhaps you've put it in the [media directory](https://github.com/cmacmackin/ford/wiki/Project-File-Options#media_dir)? But unless you do something like that, FORD won't copy over a non-Fortran file into the output on its own, so linking to it would be a moot point.

**Comment by lstagner** [comment]
Yes its a non-fortran source file and it is specified by extra_filetypes. I can already link to it using the usual methods. I just think it would be nice to have way to link to it without disrupting the flow of the documentation.

Example:
http://d3denergetic.github.io/FIDASIM/sourcefile/source_file.pro.html
There are many more files like it.

**Comment by cmacmackin** [comment]
Fixed this as part of issue #145 .
