### ISSUE TITLE
Option to check for broken links

### ISSUE THREAD

**Issue by lstagner** [cmacmackin/ford#125]
In a large project its hard to keep track of what’s linked to what. While obviously this isn't a problem for links using the `[[object]]` syntax, standard markdown links can often break. I would be a nice feature to run a link checker after the HTML documentation is generated.

**Comment by zbeekman** [comment]
While I agree that this would be convenient, I feel like there are other priorities/feature requests that should probably be much higher up the queue, since there exist a *ton* of web dev tools to perform this task already. Just my $0.02 :smiley:

**Comment by lstagner** [comment]
Yes, I agree. In fact after writing this issue I found [LinkChecker](http://wummel.github.io/linkchecker/) which suits my purposes. I just now have it run after Ford in my makefile. Perhaps this should be included in the wiki.

**Comment by cmacmackin** [comment]
I don't think I'll integrate a link checker into FORD. As you say, judicious use of makefiles allows a dedicated tool to be run after the documentation has been generated.
