### ISSUE TITLE
Documentation ignored after first empty line

### ISSUE THREAD

**Issue by aradi** [cmacmackin/ford#130]
It seems, as if Ford stopped parsing the documentation when encountering an empty line. Given the code
~~~
module test
  implicit none
  
contains

  !> Tests some feature
  !!
  !! Example:
  !!
  !! ```
  !!  call test(1)
  !! ```
  !!
  subroutine testme(param)
    integer, intent(in) :: param
    
  end subroutine testme

end module fortyxima_filesys
~~~  

the documentation of the subroutine only includes the first line (`Test some feature`)

**Comment by cmacmackin** [comment]
You need to use the predocmark throughout the block of comments. 
Alternatively, you could use the predocmark_alt to initiate the block of 
comments and then just use normal comments.

On 16-04-22 09:20 PM, Bálint Aradi wrote:
>
> It seems, as if Ford stopped parsing the documentation when 
> encountering an empty line. Given the code
>
>
> the documentation of the subroutine only includes the first line 
> (|Test some feature|)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/130>
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>

**Comment by aradi** [comment]
I've tried that, but neither that nor appending the documentation after the subroutines seems to work. Maybe I make some very silly mistake, but having the project file content
```
project: Fortyxima
project_dir: ./test
output_dir: ./_build

Test me
```
and a sorurce file `test/module2.f90`:
```
module test
  !! Contains the main test routine.
  
  implicit none
  
contains

  subroutine testme(param)
    !! Tests some feature
    !!
    !! Example:
    !!     call testme(1)
    !!
    integer, intent(in) :: param
    
  end subroutine testme

end module test
```
results in a file `_build/module/test.html` which is rendered by Firefox as:
![snapshot](https://cloud.githubusercontent.com/assets/2452321/14776157/d04dd3ac-0ac4-11e6-96d7-8fff955fccee.png)

I've used the ford version 4.5.4 as installed py pip. This time, I've tried with python 2.7.6. Any ideas?

**Comment by cmacmackin** [comment]
If you follow the "testme" link to the dedicated documentation page for that routine you'll see the full documentation. In the module page, only the summary of the documentation is shown which is, by default, the first paragraph. You can set your own summary by adding `summary: ` to the procedure's documentation's metadata.

**Comment by aradi** [comment]
Oh, sorry, my Doxygen-trained eyes became apparently short-sighted. You're right, the documentation is complete, provided, one looks at the right place!
