### ISSUE TITLE
do concurrent

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#131]
The `concurrent` from `do concurrent` is being parsed as a function I think. See below:

```fortran
  do concurrent (i=1:n)
    lcase(i:i) = lowercase_char(str(i:i))
  end do
```
![concurrent](https://cloud.githubusercontent.com/assets/6483379/14770381/cbb5949a-0a35-11e6-8b6b-63156ad0f10b.png)

**Comment by cmacmackin** [comment]
Fixed and will be in the next release.
