### ISSUE TITLE
include problems

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#134]
Even if I add `src/Funclib90`, to the `include:` meta data in the project file, `src/LibF90/turb_main.f90` has an include statement `include 'viscosity_law.f90'` where `viscosity_law.f90` lives in `src/Funclib90` and triggers a FORD error:

```
Warning: Error parsing src/LibF90/turb_main.f90.
        Can not find include file "viscosity_law.f90".
```

**Comment by zbeekman** [comment]
@cmacmackin if you need a minimal reproducer, let me know. Should be easy to work up.

**Comment by zbeekman** [comment]
huh it looks like there is also an issue:
`gfortran: unrecognized option '-cpp'`

**Comment by cmacmackin** [comment]
Which version of gfortran are you using? People have been able to use 
the preprocessing feature successfully in the past, myself included, so 
I find this an extremely weird error.

On 03/05/16 15:34, Izaak Beekman wrote:
>
> huh it looks like there is also an issue:
> |gfortran: unrecognized option '-cpp'|
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/134#issuecomment-216548399>
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>

**Comment by zbeekman** [comment]
4.3 ... on a HPC (NASA's Pleiades.... let me try loading a newer version... the gfortran error may be unique and not relevant to the error I was seeing with includes on other systems... I'll check)

**Comment by zbeekman** [comment]
OK please ignore the gfortran comment/noise.... still having problems finding includes

**Comment by szaghi** [comment]
[NASA's Pleiades](http://www.nas.nasa.gov/hecc/resources/pleiades.html) ... wow, you are a like man :smile:

**Comment by zbeekman** [comment]
@cmacmackin my suspicion is that FORD doesn't like includes that are not in the current, or subdirectories... so I have an include `../some_dir/some_include.f90`

**Comment by cmacmackin** [comment]
It is supposed to support the addition of other include paths in the 
project file. I thought I had tested it previously, so I'm not sure what 
the issue is.

On 03/05/16 16:16, Izaak Beekman wrote:
>
> @cmacmackin <https://github.com/cmacmackin> my suspicion is that FORD 
> doesn't like includes that are not in the current, or 
> subdirectories... so I have an include |../some_dir/some_include.f90|
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/134#issuecomment-216561062>
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>

**Comment by zbeekman** [comment]
I'll try to get a reproducer soon.

**Comment by cmacmackin** [comment]
I've identified and fixed a bug which can occur if you use a `~` for your home directory when setting the include path. However, I can't reproduce the problem when specifying the include directories using relative paths.

**Comment by zbeekman** [comment]
Sorry I haven't had a chance to look into this more... it's still on my radar, however...

**Comment by cmacmackin** [comment]
Did  you ever identify what this problem was?

**Comment by cmacmackin** [comment]
As I haven't heard anything more about this bug I am going to close it. FORD's handling of directory identification has been improved recently (see #177 and #194) so those might help anyway.
