### ISSUE TITLE
Lists in documentation sections

### ISSUE THREAD

**Issue by hornekyle** [cmacmackin/ford#135]
It would be nice to be able to put lists (or even checkboxes) into @note and @todo sections in the documentation.

**Comment by cmacmackin** [comment]
I'll add support for this in the medium-term. It will probably require that I add some new syntax for those environments.

**Comment by hornekyle** [comment]
Maybe the @todo and the list could both just be contained within <p> or <div> tags to denote their connection?

**Comment by cmacmackin** [comment]
I'm thinking that I'll need to add an `endnote` tag or something, so that the environments can contain multiple paragraphs, lists, etc.

**Comment by hornekyle** [comment]
That makes good sense to me.

**Comment by cmacmackin** [comment]
Added and will be in the next release.
