### ISSUE TITLE
Preprocessor file extensions

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#137]
Suggestion: allow for user-specified file extensions to use for the preprocessing option (rather than just assuming that the all uppercase ones are to be preprocessed). So, something in the project file like:
````yml
preprocessor_extensions: .fff90
````
If not present, then it does what it does now.

**Comment by cmacmackin** [comment]
Something like this has been at the back of my mind for awhile. I think 
the only reason I didn't do this from the beginning was laziness.

On 16-05-16 05:42 PM, Jacob Williams wrote:
>
> Suggestions: allow for user-specified file extensions to use for the 
> preprocessing option (rather than just assuming that the all uppercase 
> ones are to be preprocessed). So, something in the project file like:
>
> processor_extensions: .fff90
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/137>
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>

**Comment by jacobwilliams** [comment]
That's a valid reason! :)

**Comment by cmacmackin** [comment]
I've added this feature and it will be in the next release.
