### ISSUE TITLE
LaTeX in 4.6

### ISSUE THREAD

**Issue by acroucher** [cmacmackin/ford#141]
I just upgraded FORD here to 4.6.0., and now my LaTeX equations aren't being rendered any more. Anyone else seeing a problem with this?

**Comment by cmacmackin** [comment]
Someone else has alerted me to this problem as well. You'll find that if
you view the docs over HTTP or HTTPS then the latex will show up fine. I'll
try to get a bug fix out soon.

**Comment by cmacmackin** [comment]
Fixed this now.

**Comment by acroucher** [comment]
Thanks, that's great!
