### ISSUE TITLE
Block Data

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#147]
This is not really a priority since it involves obsolete Fortran, but I wanted to log it. I have a third-party file that is using BLOCK DATA, which is causing FORD to issue the following error:
````
Exception: Found DATA statement in SOURCEFILE
````
The file is basically this:
````Fortran
    block data blah
    !...some variables
    end block data
````
I suppose a workaround would be to treat it the same way you treat a module. I'm not super familiar with block data, but it looks to be an old timey to declare some variables in a file. Instead of ```use blah```, it has ```external blah``` in the routines that are using it.

**Comment by cmacmackin** [comment]
As a temporary fix I've inserted code to prevent FORD from crashing when encountering such a structure. At some point, I will add actual support for it.

**Comment by cmacmackin** [comment]
Added full support for these constructs. Although, seeing as I haven't added support for common blocks yet, I'm not sure how much use that will be...
