### ISSUE TITLE
Variables that start with "is"

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#148]
There seems to be a problem if certain variables are named `is` (or start with `is`) .  Example:

````Fortran
module test

implicit none

type,public :: is
end type is

end module test
````

Produces the error:

````
Warning: Error parsing src\test.f90.
        Bad declaration of variable type type: type,public :: is
````

**Comment by cmacmackin** [comment]
You say this is an issue if certain variables have this name, but you 
show a type declaration. Does this pose a problem for variable names too?

On 07/06/16 16:03, Jacob Williams wrote:
>
> There seems to be a problem if certain variables are named |is| (or 
> start with |is|) . Example:
>
> module  test
>
> implicit none
>
> type,public  ::  is
> end type is
>
> end module  test
>
> Produces the error:
>
> |Warning: Error parsing src\test.f90. Bad declaration of variable type 
> type: type,public :: is |
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/148>, or mute the thread 
> <https://github.com/notifications/unsubscribe/AHxJPQSOgREmTZl88w6EuEyT5vfB3qSmks5qJYhZgaJpZM4IwBg7>.
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>

**Comment by jacobwilliams** [comment]
Oh, sorry. I meant type declaration. I haven't checked if it also applies to variable names... Will do so and get back to you.

**Comment by jacobwilliams** [comment]
Variable names seem OK. Just types declarations (note: anything like `is_a`, `isa`, etc. all have the same problem. Very odd.

**Comment by cmacmackin** [comment]
Turned out the type declarations were falling afoul of the check I'd added to ensure that a `type is()` construct doesn't get confused as a type declaration. I fixed the test so that it shouldn't object to legitimate type declarations anymore.
