### ISSUE TITLE
Environment variables for project file entries

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#149]
Just an idea: What if FORD expanded entries in the project file for environment variables. That might be handy for easily changing things as part of an automated build. So, for example:

````
preprocessor: ${MY_PREPROCESSOR}
````

**Comment by cmacmackin** [comment]
Done and will be in the next release. I implemented this as a Markdown extension, which can be found [here](https://github.com/cmacmackin/md-environ).
