### ISSUE TITLE
Todo environment labeled as 'Note'

### ISSUE THREAD

**Issue by hornekyle** [cmacmackin/ford#152]
When using a @todo section, the final documentation labels the section as 'Note'.

It looks like the problem is in sub_nodes(docs) from utils.py. I changed my local copy to the following which produced a label that matches the type of environment:

```python
def sub_notes(docs):
    """
    Substitutes the special controls for notes, warnings, todos, and bugs with
    the corresponding div.
    """
    def substitute(match):
        ret = "</p><div class=\"alert alert-{}\" role=\"alert\"><h4>{}</h4>" \
              "<p>{}</p></div>".format(NOTE_TYPE[match.group(1).lower()], match.group(1).title(), match.group(2))
        if len(match.groups()) >= 4 and not match.group(4): ret += '\n<p>'
        return ret
    for regex in NOTE_RE:
        docs = regex.sub(substitute,docs)
    return docs
```

The key change is the `<h4>{}</h4>` and its matching `match.group(1).title()`.

Thanks for all the hard work on the new release too!

**Comment by cmacmackin** [comment]
Thanks, I've fixed that and will put out a patch release momentarily. I really have no excuse for missing this one, as I was looking right at this output while I was implementing things.

**Comment by hornekyle** [comment]
We all miss obvious things some times. Thanks for the quick fix.
