### ISSUE TITLE
exclude_dir within src_dir

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#155]
I don't think it works when excluding a directory that is within the `src_dir`. Like so:

````markdown
src_dir: ./src
exclude_dir: ./src/tests
````
The files in `./src/tests` are still being parsed.

**Comment by cmacmackin** [comment]
Fixed and will be in the next release, out today or tomorrow.

**Comment by cmacmackin** [comment]
Just authored a release fixing this.
