### ISSUE TITLE
extra_filetypes

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#156]
I can't seem to get the `extra_filetypes` feature to work. I have this in my project file for a Fortran include file:

``` markdown
extra_filetypes: .inc !
```

But it doesn't seem to be parsing the `.inc` file in my `src_dir`.

**Comment by cmacmackin** [comment]
Is this still an issue for you?

**Comment by jacobwilliams** [comment]
Yes, it still doesn't work for me. This is for [json-fortran](https://github.com/jacobwilliams/json-fortran/blob/master/json-fortran.md). The `src/json_macros.inc` file is not being shown in the documentation.

**Comment by jacobwilliams** [comment]
Oops, I just realized that It works fine if I leave out the dot. So ```extra_filetypes: inc !``` works.
