### ISSUE TITLE
New 5.0.4 Failing with FURY sources

### ISSUE THREAD

**Issue by szaghi** [cmacmackin/ford#165]
@cmacmackin 

Hi Chris, trying to build the API of [FURY](https://github.com/szaghi/FURY) I fall into this error

https://travis-ci.org/szaghi/FURY#L658

> Traceback (most recent call last):
  File "/home/travis/.local/bin/ford", line 9, in <module>
    load_entry_point('FORD==5.0.4', 'console_scripts', 'ford')()
  File "/home/travis/.local/lib/python2.7/site-packages/ford/__init__.py", line 356, in run
    main(proj_data,proj_docs,md)
  File "/home/travis/.local/lib/python2.7/site-packages/ford/__init__.py", line 319, in main
    project.correlate()
  File "/home/travis/.local/lib/python2.7/site-packages/ford/fortran_project.py", line 205, in correlate
    if type(container) != str: container.correlate(self)
  File "/home/travis/.local/lib/python2.7/site-packages/ford/sourceform.py", line 835, in correlate
    self.pub_vars.update([v for v in variables if v in self.public_list])
ValueError: dictionary update sequence element #0 has length 14; 2 is required

I think I have missed some of the news about the 5.0.4 incompatibilities...
I have updated the old project file using the *relative* paths and set "search: false" to be sure that I have not introduced *strange correlations*, see the complete [file]( https://raw.githubusercontent.com/szaghi/FURY/master/doc/main_page.md)

Have you any suggestions?

**Comment by cmacmackin** [comment]
This is a really weird error. I'm trying to figure out exactly what Python
even means by "dictionary update sequence element #0 has length 14; 2 is
required". Unfortunately I am at home without internet (waiting for someone
to come and repair it) at the moment, so this will have to wait a bit.

**Comment by szaghi** [comment]
@cmacmackin fortunately you are not in Italy, otherwise you internet connection will be repaired in September, Italy is OFF in August :cry: 

I will try to investigate more, thank you very much as always.

**Comment by victorsndvg** [comment]
Hi,

I'm a newbie  with FORD, but I'm experiencing the same problem trying to document  [XH5For](https://github.com/victorsndvg/XH5For) with 5.0.4 .

It seems that commenting lines 831-835 in sourceform.py avoid the crash. Of course is not a solution, only a single clue...

Congratulation for your great work with this project @cmacmackin  !

**Comment by szaghi** [comment]
@victorsndvg you are my Angel... I was facing with this problem with almost all my Fortran codes...

**Comment by cmacmackin** [comment]
Fixed and will be in the next release, out today or tomorrow.

**Comment by szaghi** [comment]
Thank you very much Chris you are my preferred rockstar!

**Comment by cmacmackin** [comment]
Just authored a release fixing this.
