### ISSUE TITLE
Alternate installation options?

### ISSUE THREAD

**Issue by rouson** [cmacmackin/ford#167]
Is there any plan to offer additional installation options?  If there would be any interest in adapting the bash installer that [OpenCoarrays](https://github.com/sourceryinstitute/opencoarrays) uses, I would be glad to help.  The primary benefit is that bash is ubiquitous on Linux and OS X and presumably will increasingly become ubiquitous on Windows now that Microsoft offers an [Ubuntu subsystem for Windows 10](https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/#rF2Y1VSLMdZE81yA.97).

For anyone who is not already a Python user, the pip option is daunting.  I'm interested installing FORD in the virtual machine that is offered for free in the Sourcery Institute [store](http://www.sourceryinstitute.org), which is based on Lubuntu 12 and has python 2.7.3 installed.  The pip installation option is somewhat daunting because it leads to several questions and concerns, including

1. The pip [installation page](https://pip.pypa.io/en/latest/installing/#using-linux-package-managers) contains the following warning: "Be cautious if you're using a Python install that's managed by your operating system or another package manager. get-pip.py does not coordinate with those tools, and may leave your system in an inconsistent state."  Consequently, I'm attempting to update to a newer version of python using apt-get.  That in itself is a little daunting because of the need to understand and run several apt-get commands, including [update, upgrade, and/or dist-upgrade](http://askubuntu.com/questions/94102/what-is-the-difference-between-apt-get-update-and-upgrade), some of which can be rather time-consuming.   I will report back if that works.  If not, I'm very hesitant to attempt to update python by other means given the aforementioned warning.

2. Is it smarter to upgrade to a 2.x version or a 3.x version.  Given the incompatibility between the two, it's especially hard for a non-python-programmer to decipher the implications of one versus the other.  If there's a preferred choice for FORD, it would be great to have that information in the FORD README.  Actually, even if neither is preferred, that's great information too because it saves a lot of searching and worry about whether one has made the better choice.

I have considered installing and adopting FORD several times over the past year or two.  I've stopped short every time because of this hurdle.  I am very interested in switching from ROBODoc to FORD in several [classes](http://www.sourceryinstitute.org/classes.html) that I will teach this Fall. I would greatly appreciate some guidance.

**Comment by szaghi** [comment]
@rouson I replay before Chris just for a coincidence, I could be wrong. Anyway it seems that Chris *registered* FORD on PyPi by setuptools, it seems that the setup.py file is shipped with FORD repository, si it dhould be trivial to install FORD by your great installer. Just clone the repo (or dowonload an archive of the release) and invoke the setup.py file. I am with a smartphone, I cannot provide a snippet code, but I think it is vety simple to avoid pip, Chris provided all files you need.

Cheers.

**Comment by rouson** [comment]
@szaghi Thanks for the pointer.  I hope you won't mind my advising against describing processes as "trivial."  Even things that seem trivial to the informed can prove challenging to many others. Could someone please post explicit instructions on how to use setup.py.  If so, I would be glad to submit a pull request that adds the instructions to the README file.  It would be ideal to have a line-by-line transcript of what to do. 

Becasue my attempt to upgrade python to a new version failed, I just created a new Lubuntu Linux 16 virtual machine because it provides a pre-installed python 2.7.11.  A transcript of my next step follows:

$ python setup.py 
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

so I'm guessing that I now need to know how to get the module setuptools.

**Comment by rouson** [comment]
I searched the web for "python setuptools" and found instructions this [page](https://pypi.python.org/pypi/setuptools#installation-instructions) that provides an [ez_setup.py](https://bootstrap.pypa.io/ez_setup.py) file for installing setuptools.  Downloading that file and executing `python ez_setup.py` appears to successfully install setuptools.  My next step was
```
$ python setup.py build
$ sudo python setup.py install
```
The `build` step appeared to complete successfully.  The `install` step appears to have installed several packages successfully but terminated with the error message at the bottom of the text below when attempting to install markdown:
```
Searching for markdown-include>=0.5.1
Reading https://pypi.python.org/simple/markdown-include/
Downloading https://pypi.python.org/packages/ef/44/eb6e9b4fa1110b719abb876c9b6dd8b46af886a94536ec4e9117fe5e7b97/markdown-include-0.5.1.tar.gz#md5=0a88e7330f088a0387493265a81c0353
Best match: markdown-include 0.5.1
Processing markdown-include-0.5.1.tar.gz
Writing /tmp/easy_install-Kyu36r/markdown-include-0.5.1/setup.cfg
Running markdown-include-0.5.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Kyu36r/markdown-include-0.5.1/egg-dist-tmp-cwwC2l
zip_safe flag not set; analyzing archive contents...
Moving markdown_include-0.5.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding markdown-include 0.5.1 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/markdown_include-0.5.1-py2.7.egg
Searching for markdown
Downloading https://pypi.python.org/packages/ef/44/eb6e9b4fa1110b719abb876c9b6dd8b46af886a94536ec4e9117fe5e7b97/markdown-include-0.5.1.tar.gz#md5=0a88e7330f088a0387493265a81c0353
Best match: markdown include-0.5.1
Processing markdown-include-0.5.1.tar.gz
Writing /tmp/easy_install-si5gO_/markdown-include-0.5.1/setup.cfg
Running markdown-include-0.5.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-si5gO_/markdown-include-0.5.1/egg-dist-tmp-Js0iol
zip_safe flag not set; analyzing archive contents...
Removing /usr/local/lib/python2.7/dist-packages/markdown_include-0.5.1-py2.7.egg
Moving markdown_include-0.5.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
markdown-include 0.5.1 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/markdown_include-0.5.1-py2.7.egg
error: The 'markdown' distribution was not found and is required by markdown-include, md-environ, FORD
```

Any advice?

**Comment by szaghi** [comment]
@rouson Hi Damian, I am still not in front of a pc, so I cannot help before tomorrow. If Chris does not give you the snippet before tomorrow morning I will try to do it. From a quick view with my *deading* smartphone it seems that your installatiin missed the markdown module that is a fundamental requirement for FORD. I cannot inspect the setup.py now, but I am quite sure that the requirements are listed there (sometimes pythoners put them into a requirements.txt file sourced by setup.py). Let me access to a pc tomorrow  (no one at home) and I could be of more help (if Chris cannot do it before me).

Good night!

**Comment by zbeekman** [comment]
@rouson How do you maintain/ship/edit the Lubuntu image?

I think 2.7.3 is pretty old... so I wouldn't be surprised if you need to update python, but have not confirmed this to be true

The `pip` package management is actually quite easy once it's setup correctly on your system... what happens when you type `ls -l $(which pip)`?

Pip handles all the dependencies too, which is one of its main advantages and you probably want to install graphviz as well, from the package manager.

**Comment by cmacmackin** [comment]
Sorry for the delay in my response. I've been quite busy lately with studies and other projects. Pip really is the easiest route to take because, as @zbeekman says, it handles all of the dependencies for you. It also installs things using the standard Python directory structure, which is not something I would trust an installer I hand-write myself to do properly. Pip can be installed as follows:
```
sudo apt-get install python-pip python-dev build-essential
```
If you don't want pip to install software into the system path (which I don't think is _too_ risky, but nonetheless I understand why you want to avoid it) then you can install it locally in your home directory:
```
pip install --user ford
```
This will cause its files to be installed in `$(HOME)/.local`. You will need to add `$(HOME)/.local/bin` to your PATH.

Whether you use Python 2.7 or some version of Python 3 shouldn't matter; FORD was written to be able to use both. As it was written and tested on a machine running 2.7 you might be slightly better off with that.

**Comment by rouson** [comment]
@cmacmackin Thanks! I just forked and submitted a pull request that updates the installation instructions to include th ```sudo apt-get install...`` line that you provided.
