### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#17]
I find that people interpret release version strings differently, and really like the philosophy behind [semantic versioning](http://www.semver.org).

Do you have a well defined policy for versioning releases?

Would it make sense to adopt semantic versioning?

I know people often have trepidation about bumping a release of new software from 0.x—which they may think connotes some sort of new-ness or immaturity of the package—to 1.x, fearing some sort of over promise in terms of stability, function and lack of bugs. I find, however, that software will always have bugs, and clarity about API consistency, functionality and backwards compatibility far out weigh any concerns of  over promising.

**Comment by cmacmackin** [comment]
I didn't have a specific policy yet, although was using a semantic-ish approach. I think I will adopt semantic versioning from here on out. I will point out that I haven't specifically broken with semantic versioning yet, as major-version 0 is allowed to break the API between minor versions. However, I think at this point I'm ready to release a stable API.

**Comment by szaghi** [comment]
Good news :-)
