### ISSUE TITLE
slow rendering of large graphs

### ISSUE THREAD

**Issue by Schildkroete23** [cmacmackin/ford#176]
Large call graphs get rendered very slow. I think this is caused by increasing the number of [SVG elements drain performance exponentially](http://frozeman.de/blog/2013/08/why-is-svg-so-slow/). So this is a general SVG problem and can't be fixed easily. However reducing the number of SVG elements could be a solution. Is there a way to set the depth of the graphs?

**Comment by cmacmackin** [comment]
#197 addressed this to the extent possible.
