### ISSUE TITLE
SVG images are not being rendered

### ISSUE THREAD

**Issue by lstagner** [cmacmackin/ford#187]
Sometime between v5.0.4 and v5.0.6 the SVG images in my [site](http://d3denergetic.github.io/FIDASIM/page/index.html) are no longer rendered.

**Comment by zbeekman** [comment]
Just chiming in to say beautiful docs, @lstagner!

**Comment by cmacmackin** [comment]
Do you mean the graphs? They're rendering just fine on my browser. My cursory glance didn't show any other SVGs.

**Comment by lstagner** [comment]
Take a look [here](http://d3denergetic.github.io/FIDASIM/page/02_physics/02_atomic_tables.html#hydrogen-hydrogen-interactions) its really noticeable. It used to show a whole bunch of figures showing the atomic cross sections.

**Comment by cmacmackin** [comment]
I suspect this is an issue with the version of the markdown library which you're using and not with FORD per se. I notice that when specifying your image source, the names are things like `|media|/H_H_ioniz.svg H-H Ionization`. The text after the `.svg` might be causing the problem. Also, you don't seem to have any filles with those sorts of names in your media directory.

**Comment by lstagner** [comment]
Looks like your right. The text after the filename is supposed to be the title of the image that pops up when you hover your mouse over it. It looks like the markdown parser used to accept the the title to be anything after the filename but it now requires that requires quotation marks e.g. `|media|/H_H_ioniz.svg "H-H Ionization"`
