### ISSUE TITLE
Lists in variable comments

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#188]
Sometimes the documentation for a single variable can be quite large. I think it would be nice to be able to include more complicated formatting, such as lists. So, something like this:
```fortran
integer :: x  !! valid values:
              !! * 'fast'  
              !! * 'slow'  
```
and have it be rendered as a list. Currently, I think it can only render variable comments in paragraph form.
For example, see the `iflag` variable [here](http://jacobwilliams.github.io/bspline-fortran/proc/db6ink.html).

**Comment by cmacmackin** [comment]
Have you tried using Markdown list formatting? The documentation for variables should be run through the Markdown processor, so that should work. In the variable you mention, you didn't use any list formatting in your documentation comments.

**Comment by jacobwilliams** [comment]
I thought I had tried it in the past. I'll check again to make sure, maybe I was doing it wrong.

**Comment by cmacmackin** [comment]
Keep in mind that your above example wouldn't render properly, as you need a space between the paragraph and the list. It should be:
```fortran
integer :: x  !! valid values:
              !!
              !! * 'fast'  
              !! * 'slow'  
```

**Comment by jacobwilliams** [comment]
Ah ha! That must be what I was doing wrong! Thanks!!
