### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#19]
Python 3 support would be great.

**Comment by jacobwilliams** [comment]
Note: I've got a working Python3 version at https://github.com/jacobwilliams/ford. I can clean it up and make sure it's backward compatible for Python2, and send it as a pull request if you're interested.

**Comment by cmacmackin** [comment]
That would be great. I was thinking that it would be good to get Python3 
support even before your Issue, but have no experience porting code to 
it. However, I notice that you commented out some of the try/except 
structures that I set up. I'd prefer if those were inserted back in to 
the main edition for two reasons:

1. I find that, while useful in developing, backtraces look somewhat 
unprofessional in production-quality code.
2. If an error is encountered while processing a file, I would like FORD 
to be able to continue on with other files and not have to abort.

By the way, I take it my Markdown-Include plugin was already Python3 
compatible?
On 20/01/15 12:44 AM, Jacob Williams wrote:
>
> Note: I've got a working Python3 version at 
> https://github.com/jacobwilliams/ford. I can clean it up and make sure 
> it's backward compatible for Python2, and send it as a pull request if 
> you're interested.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/19#issuecomment-70604036>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by jacobwilliams** [comment]
-Yes, I can add the try structure back.  Totally agree.  It was just for my debugging purposes.
-Markdown-Include required a minor change for the print() statement.  I can send that to you as well of you want.

**Comment by cmacmackin** [comment]
I'll just do that one myself.
On 20/01/15 12:56 AM, Jacob Williams wrote:
>
> -Yes, I can add the try structure back. Totally agree. It was just for 
> my debugging purposes.
> -Markdown-Include required a minor change for the print() statement. I 
> can send that to you as well of you want.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/19#issuecomment-70604677>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by jacobwilliams** [comment]
Sure thing.  Just use print() with the parentheses, and then put ````from __future__ import print_function```` at the top of the file, and then it will work with both 2 and 3.

**Comment by cmacmackin** [comment]
Thanks a lot for the work you put into porting FORD to python3! It's very much appreciated!
