### ISSUE TITLE
MathJax extension doesn't work with nested/recursive patterns

### ISSUE THREAD

**Issue by cbcoutinho** [cmacmackin/ford#196]
Howdy @cmacmackin,

Just ran into a LaTeX issue w.r.t. nested arrays, namely an array of arrays. I'm trying to create the following:

![example](https://cloud.githubusercontent.com/assets/12901868/22605666/2e7edf36-ea51-11e6-91c3-3b834263cb90.png)

But it's turning into horizontally aligned arrays instead of vertically aligned ([see my hosted doc](https://cbcoutinho.github.io/learn_dg/proc/getjacobian.html))

I think it has to do with what the built in MJ extension considers a group ([link to ford/md_mathjax.py](https://github.com/cmacmackin/ford/blob/master/ford/mdx_mathjax.py#L41-L43)) - is it possible there's an issue related to recursion?

For an example: I've created two examples conveying the same data information - the first is what I would prefer and is being produced correctly, the second is my hackish workaround. The following LaTeX doc is produced on my machine, but the second array is incorrectly formatted in FORD:

```
\documentclass{article}
\usepackage{amsmath}

\begin{document}

% This is my hack
\[ X = \left[ \begin{array}{rcl}
      x_1 & & y_1 \\
      x_2 & & y_2 \\
      & \vdots & \\
      x_{N-1} & & y_{N-1} \\
      x_N & & y_N \\
  \end{array} \right]\]

% This one is being incorrectly rendered
\[ X = \left[ \begin{array}{c}
     \begin{array}{cc}
       x_1 & y_1 \\
       x_2 & y_2
     \end{array} \\
     \vdots \\
     \begin{array}{cc}
       x_{N-1} & y_{N-1} \\
       x_N & y_N
     \end{array} \\
   \end{array} \right]\]

\end{document}
```

**Comment by cmacmackin** [comment]
This is an extremely odd error. It seems that _some_ (but not all) of your double backslashes are being interpreted somewhere as escaping a backslash and the output in the HTML file is
```latex

\[ X = \left[ \begin{array}{c}
  \begin{array}{cc}
    x_1 &amp; y_1 \\
    x_2 &amp; y_2
  \end{array} \
  \vdots \
  \begin{array}{cc}
    x_{N-1} &amp; y_{N-1} \\
    x_N &amp; y_N
  \end{array} \\
\end{array} \right]\]
```
As a temporary workaround you can write in your markdown file as 
```latex
\[ X = \left[ \begin{array}{c}
     \begin{array}{cc}
       x_1 & y_1 \\
       x_2 & y_2
     \end{array} \\\\
     \vdots \\\\
     \begin{array}{cc}
       x_{N-1} & y_{N-1} \\
       x_N & y_N
     \end{array} \\
   \end{array} \right]\]
```

**Comment by cmacmackin** [comment]
I couldn't understand what the problem was in the `mdx_mathjax.py` file, so I switched to a different, somewhat more complex Markdown extension which seems to avoid this issue. It will be in the next release.
