### ISSUE TITLE
inter-modules dependency

### ISSUE THREAD

**Issue by szaghi** [cmacmackin/ford#2]
Hi Chris, 

Very good job! Your new documentation is very useful. It is the first doctool that drives me to leave doxygen to another  tool :-)

I read that you are working to extract the inter-modules dependency of files that Ford parses. I have already faced with this problem in FoBiS.py (I see that you using it for your very nice Futility progect, great name!): I am refactoring FoBiS.py for publishing on PyPi, maybe I can create packages of the classes/functions that I wrote for FoBiS.py in order that you can easily integrate them into Ford. Are you interested in? At the end of this week when I come back to office I very curious to try Ford...

See you soon

**Comment by cmacmackin** [comment]
Actually, that is fully working right now. I use the toposort module available on PyPI. Thanks for the offer, though!

**Comment by szaghi** [comment]
Happy to know it. Toposort seems interesting, thanks again!

Il giorno 13:41 lun 05/gen/2015 Chris MacMackin <notifications@github.com>
ha scritto:
