### ISSUE TITLE
Comments for arguments declared on same line

### ISSUE THREAD

**Issue by samharrison7** [cmacmackin/ford#206]
Just getting started with FORD and I really like what I see so far. So, thanks!

I've got a comment/suggestion re commenting arguments. If a procedure has a lot of comments, I often declare them on the same line:

```fortran
function my_function(a,b,c,d,e,f,g) result(my_result)
    real :: a,b,c,d,e,f,g,my_result
    ...
end function
```

But, as far as I can tell, the only way to comment on each argument individually would be to do something like this:

```fortran
function my_function(a,b,c,d,e,f,g) result(my_result)
    !> Description of a
    real :: a
    !> Description of b
    real :: b
    !> Description of c
    real :: c
    ....
end function
```

I was wondering about the possibility to have functionality to comment on arguments in the procedure's comment, something like this:

```fortran
!> Description of my_function
!! @param a Description of a
!! @param b Description of b
!! ...
function my_function(a,b,c,d,e,f,g) result(my_result)
    real :: a,b,c,d,e,f,g
    ...
end function
```

**Comment by jacobwilliams** [comment]
FYI: you can also comment them in line like this:
```fortran
real :: a  !! Description of a
real :: b  !! Description of b
```
(in this case, I'm setting `docmark` to `!`). 

It's just my opinion, but I'd recommend against what you are suggesting. That's how I commented for years using a different documentation tool. Ultimately, it was very cumbersome and error prone to have to maintain two separate lists of the variable names. The great thing about FORD is you don't have to do that.

**Comment by samharrison7** [comment]
Thanks @jacobwilliams, I think I'm coming around to that conclusion too. I guess it just felt a bit odd at first after using other different documentation tools!
