### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte

### ISSUE THREAD

**Issue by janusw** [cmacmackin/ford#208]
I'm trying to run FORD on a large Fortran project with this simple config:

```
src_dir: ./src
include: ./src/include
output_dir: ./ford-doc
fpp_extensions: F,f90
predocmark: >
docmark_alt: #
predocmark_alt: <
display: public
         protected
         private
source: false
graph: true
search: true
```

The output shows a lot of lines saying "Reading file src/*.f90" with all of my source files, and then in the end I see:

```
Processing documentation comments...
Traceback (most recent call last):
  File "/usr/local/bin/ford", line 9, in <module>
    load_entry_point('FORD==5.0.6', 'console_scripts', 'ford')()
  File "/usr/local/lib/python2.7/dist-packages/ford/__init__.py", line 357, in run
    main(proj_data,proj_docs,md)
  File "/usr/local/lib/python2.7/dist-packages/ford/__init__.py", line 317, in main
    project.markdown(md,'..')
  File "/usr/local/lib/python2.7/dist-packages/ford/fortran_project.py", line 279, in markdown
    src.markdown(md,self)
  File "/usr/local/lib/python2.7/dist-packages/ford/sourceform.py", line 435, in markdown
    if isinstance(item, FortranBase): item.markdown(md,project)
  File "/usr/local/lib/python2.7/dist-packages/ford/sourceform.py", line 309, in markdown
    self.doc = md.convert(self.doc)
  File "/usr/local/lib/python2.7/dist-packages/markdown/__init__.py", line 359, in convert
    source = util.text_type(source)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 7: invalid continuation byte. -- Note: Markdown only accepts unicode input!
```

So apparently one of my files has some weird character in a funny encoding. Unfortunately the error does not say anything about where this character is found.

Probably this is not really a bug in FORD as such, but simply bad user input. However, it would be very helpful to get a proper error message, telling me where the bad input character is seen.

**Comment by szaghi** [comment]
Dear @janusw can you try debug mode?

```shell
ford --debug ...
```

**Comment by janusw** [comment]
Thanks for the hint, @szaghi. However, if I use --debug, I already get an exception while reading the files:

```
Traceback (most recent call last):
  File "/usr/local/bin/ford", line 9, in <module>
    load_entry_point('FORD==5.0.6', 'console_scripts', 'ford')()
  File "/usr/local/lib/python2.7/dist-packages/ford/__init__.py", line 357, in run
    main(proj_data,proj_docs,md)
  File "/usr/local/lib/python2.7/dist-packages/ford/__init__.py", line 310, in main
    project = ford.fortran_project.Project(proj_data)
  File "/usr/local/lib/python2.7/dist-packages/ford/fortran_project.py", line 95, in __init__
    ford.sourceform.FortranSourceFile(os.path.join(curdir,item),settings, preprocessor, ext in self.fixed_extensions))
  File "/usr/local/lib/python2.7/dist-packages/ford/sourceform.py", line 1023, in __init__
    FortranContainer.__init__(self,source,"")
  File "/usr/local/lib/python2.7/dist-packages/ford/sourceform.py", line 747, in __init__
    raise Exception("Found USE statemnt in {}".format(type(self).__name__[7:].upper()))
Exception: Found USE statemnt in SOURCEFILE
```

This apparently occurs in a fixed-source file which contains a USE statement. Two issues with that:
1) While a USE statement in fixed source may be a bit unusual, I guess it's not technically forbidden in Fortran, right?
2) Spelling error: "statemnt"

Without --debug I only get a warning for this and FORD continues to process the other files.

**Comment by szaghi** [comment]
@janusw 

Hi Janus, you are much more than welcome :smile: 

> This apparently occurs in a fixed-source file which contains a USE statement.

Mmm, Chris is the master thus he will correct me, but I think that FORD is focused more on *modern* free format. I suspect that the support for fixed form is limited, but I am probably wrong and you are more fortunate.

> While a USE statement in fixed source may be a bit unusual, I guess it's not technically forbidden in Fortran, right?

I think so, the fixed of free form should not be a matter, but I have not a recent recall of what standard says. However, reading your log, I suspect that FORD complains about the usage of `use` outside a `module` or a `program`. I think it is better to wait for Chris: I am not sure about FORD support for fixed-source, non modularized projects, sorry.

Cheers

**Comment by cmacmackin** [comment]
I'd need to look at the file producing this error. Stefano is correct that FORD thinks it has found a USE statement outside of module, program, or procedure. I'm not sure why this would be. I should note that my support for fixed-form code just involves me running through a 3rd party converter before analysing it. There could be something the converter is doing which is causing problems.

**Comment by szaghi** [comment]
@cmacmackin 

Chris

>I should note that my support for fixed-form code just involves me running through a 3rd party converter before analysing it

Wow, I was not conscious of this. Can you tell me which converter you are using? Is it Pyhonic?

Cheers

**Comment by janusw** [comment]
> I'd need to look at the file producing this error. Stefano is correct that FORD thinks it has found a USE statement outside of module, program, or procedure.

That's exactly the case: A simple fixed-source file with a single subroutine, which is USEing stuff from some module. Perfectly valid Fortran AFAICS.


> I'm not sure why this would be.

Weeeell, this is one of those projects which has mostly transitioned to 'modern' Fortran (with modules and stuff), but is sprinkled with a few legacy parts that are still fixed-source F77.

This may not be good style, but it's certainly not forbidden either.

**Comment by szaghi** [comment]
> That's exactly the case: A simple fixed-source file with a single subroutine, which is USEing stuff from some module. Perfectly valid Fortran AFAICS.

Sure, but I think that it is more *subtle*: it seems that FORD *views* the `use` outside any `module`, `program`, `subroutine` or `function` directly into a source file, flying outside any `scope`. Chris suggested that this can be the consequence of a 3rd party library that converts on-the-fly your fixed-form source to a free-form before FORD parses it. In other words, FORD is not parsing directly your source file rather it is pre-processed to be formatted into free form and then parsed by FORD. It seems that this pre-processing phase alters your code generating a *flying use* statement :smile: 

> This may not be good style, but it's certainly not forbidden either.

Sure, FORD is not complain about any style choice :smile: 

Can you give us that source file (or a minimal part of it raising the issue) in order to facilitate Chris to discover where the pre-processor fails?

Cheers

**Comment by janusw** [comment]
> Can you give us that source file (or a minimal part of it raising the issue) in order to facilitate Chris to discover where the pre-processor fails?

Here is a simple reproducer:

```
      subroutine my_subroutine (aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaarg)
      use m
      end subroutine
```

With "ford --debug" I see:

```
Exception: Found USE statemnt in SOURCEFILE
```

Actually this seems to be some issue with line length: Removing one letter in the argument name makes it go away! (I'm using "gfortran -ffixed-line-length-none" to get past the 72-columns limitation.)

**Comment by cmacmackin** [comment]
The [tool](https://github.com/ylikx/fortran-legacy-tools/blob/master/fixed2free/fixed2free2.py) I was using to convert from fixed-form to free-form converted anything after character 72 to a comment. I don't want to completely eliminate this behaviour, as I have seen some old code which relies on this for comments. As such I've added a project-file option to give unlimited line-length. This will be in the next release.
