### ISSUE TITLE
version info embedded in ford executable

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#21]
I just upgraded (I think!?) to the latest patch using pip/pypi but it would be awesome if you added a `-v` or `-V` or `--version` flag so that users who install ford through that avenue can easy check which version they have…

Great work :+1:

**Comment by szaghi** [comment]
I agree! Great work!

**Comment by cmacmackin** [comment]
That's now available in version 1.1.0 (along with Python3 support).
