### ISSUE TITLE
Missing "project_dir" option in the wiki

### ISSUE THREAD

**Issue by fran-pena** [cmacmackin/ford#211]
I cannot find option "project_dir" among the [Project File Options](https://github.com/cmacmackin/ford/wiki/Project-File-Options). Has it been removed? 

Best,

**Comment by cmacmackin** [comment]
It was renamed to `src_dir` with [v5.0.0](https://github.com/cmacmackin/ford/releases/tag/v5.0.0). This was felt to be more in keeping with the naming scheme used in the project file options.

**Comment by fran-pena** [comment]
Thank you, for the quick response.

May I suggest to indicate this change in the wiki? When I searched in the whole internet, I couldn't find a hint of such replacement.

**Comment by fran-pena** [comment]
Ok, I see the explanation in the link you attached. Fair enough.
