### ISSUE TITLE
exclude multiple files

### ISSUE THREAD

**Issue by alinelena** [cmacmackin/ford#213]
built the latest version of ford... and I am trying to exclude more than one file 
with
  17 exclude: a.f90                                                                                                                      
  18 b.f90     
but when ford runs.
only a.f90 is excluded
Reading file ../source/b.f90

**Comment by haraldkl** [comment]
From your snippet it is not directly obvious, but did you indent the second line? From the [wiki](https://github.com/cmacmackin/ford/wiki/Project-File-Options):

> If a line is indented by 4 or more spaces, that line is assumed to be an additional line of the value for the previous keyword. A keyword may have as many lines as desired. [Note that these must be spaces and not tabs.]
Thus, it should look like:

    exclude: a.f90
         b.f90

**Comment by cmacmackin** [comment]
As I've never heard back about this, I'm going to assume that @haraldkl's suggestion worked and close the issue. Reopen if it is still a problem.
