### ISSUE TITLE
Force Ford to display a private implementation

### ISSUE THREAD

**Issue by leonfoks** [cmacmackin/ford#215]
I may be missing something here....

I have a public type, with public type bound procedures linked to private interfaces, the implementations of those interfaces are in submodules.  I want to force some private interfaces to appear in the documentation.  I normally exclude the submodules so as not to clutter my docs.

Can I do this? Is there a key word I can put in the source comments to force it to display the parameters? 

Also, In my ford.md I turned off private display, because I dont need every single private func/sub to be displayed. Just some of them.

display: public
         protected

 Here's what the private interface to a public type bound procedure looks like in the html docs.  Below is a short example of what I mean.

This may be an unrelated issue, but the private interface still shows up even though I turned off private display, it just doesnt list the arguments like a public func/sub.

Thanks!

##### None

```fortran
module m_thisType

private

public :: thisType

type thisType
  !! A test type
  real :: a
    !! a real member
  integer :: b
    !! b int member
contains
  procedure, public :: aTBP => aTBP_thisType
    !! Type bound procedure thisType%aTBP()
end type

interface
  !! Overloaded type bound procedure thisType%aTBP()
  module subroutine aTBP_thisType(this, c)
    !! This is private by default, but I want the user to see how to use this procedure
    class(thisType) :: this
    real :: c
      !! value to print
  end subroutine
end interface
end module

submodule (m_thisType) sm_thisType_a
  !! contains implementation of the ancestor modules interface but i exclude this from Ford processing.
end submodule
```

**Comment by cmacmackin** [comment]
Thanks for the bug report. This turned out to be due to FORD not properly displaying type-bound procedures pointing to interfaces (using submodules or otherwise). I've fixed this and it will be in the next release.
