### ISSUE TITLE
Ford ignores "True" for graph option

### ISSUE THREAD

**Issue by leonfoks** [cmacmackin/ford#219]
This is pretty minor, but if I use "graph: True" instead of "graph: true",  Ford states it is generating the graphs but then does not.

Perhaps a str.lower() when it reads the options might do the trick?

**Comment by haraldkl** [comment]
I believe cd176794090af95ba5b2d1e659d7a6c678c1c87f would fix this.

**Comment by cmacmackin** [comment]
I've merged PR #220 to address this.
