### ISSUE TITLE
Build doesn't work with markdown-2.6.11

### ISSUE THREAD

**Issue by lstagner** [cmacmackin/ford#221]
The recent update has broken my FIDASIM build.
https://travis-ci.org/D3DEnergetic/FIDASIM/builds/327013190#L758

**Comment by lstagner** [comment]
I took a bit of time to track down the issue I have with my build. The problem is that the markdown version that is installed changed. The version of markdown that worked for me was markdown-2.6.9. The markdown that is now being installed in my build is markdown-2.6.11.

Is there anyway to fix the markdown version that is used?

**Comment by cmacmackin** [comment]
Confirmed that the new LaTeX plugin being used (see #196) does not experience this problem. The next release will therefore work with the latest version of Markdown.
