### ISSUE TITLE
`exclude_dir` option seems to be broken.

### ISSUE THREAD

**Issue by vdikan** [cmacmackin/ford#227]
Hello, Chris. Thanks for a great tool! FORD looks like it can help me with my  Ph.D a lot. 

While playing with it I noticed that `exclude` option works as expected (both in the project-file and cli), but `exclude_dir` does not. Is that a bug or just mis-usage? (I tried typing just folder names and relative paths as well, it didn't work).

**Comment by vdikan** [comment]
Well, I was wrong about `exclude_dir` not working at all. But you need to provide full relative path, not as it says in the wiki:
> Provide only the directory name.

So, if e.g. you want to ban `temp` folder in your project sources, and you have `src_dir: ./Src/fordtest/`, put `exclude_dir: ./Src/fordtest/temp`.

I was wrong because a markdown comment line in the projectfile is actually treated like end of paragraph.  So everything I specified after some comments went to the frontpage project overview.

**Comment by zbeekman** [comment]
Fixed [the wiki page](https://github.com/cmacmackin/ford/wiki/Project-File-Options). Recommend closing this issue.
