### ISSUE TITLE
MD-include-path change

### ISSUE THREAD

**Issue by szaghi** [cmacmackin/ford#23]
Hi all,

I have just downloaded the latest version and I am currently using it on Lib_VTK_IO. It seems that the new version has an API change not documented.

In the previous version the path of included md files was relative to the path of the project main file. Now it seems that the path is relative to the path where ford is executed.

See you soon.

**Comment by cmacmackin** [comment]
Oh dear, that certainly wasn't supposed to happen. I'll have to track 
down that bug.
On 21/01/15 06:05 AM, Stefano Zaghi wrote:
>
> Hi all,
>
> I have just downloaded the latest version and I am currently using it 
> on Lib_VTK_IO. It seems that the new version has an API change not 
> documented.
>
> In the previous version the path of included md files was relative to 
> the path of the project main file. Now it seems that the path is 
> relative to the path where ford is executed.
>
> See you soon.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/23>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by cmacmackin** [comment]
Okay, that should be fixed now. When I reorganized my Markdown-Include feature into its own module I forgot to change how I specified the settings when initializing Markdown. You'll also need to get the latest version of Markdown-Include, as the old version seemed to have some issues when passing it configurations.
