### ISSUE TITLE
Graphs failure

### ISSUE THREAD

**Issue by vdikan** [cmacmackin/ford#231]
Graphs do not work with the github version of FORD. When I try to include them in the build I get an exception:
```
Creating HTML documentation...
Generating graphs...
100%|████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:01<00:00,  8.69/s]
Traceback (most recent call last):
  File "/usr/local/bin/ford", line 11, in <module>
    load_entry_point('FORD', 'console_scripts', 'ford')()
  File "/home/dix/code/python/ford/ford/__init__.py", line 382, in run
    main(proj_data,proj_docs,md)
  File "/home/dix/code/python/ford/ford/__init__.py", line 369, in main
    docs = ford.output.Documentation(proj_data,proj_docs_,project,page_tree)
  File "/home/dix/code/python/ford/ford/output.py", line 138, in __init__
    self.graphs.graph_all()
  File "/home/dix/code/python/ford/ford/graphmanager.py", line 118, in graph_all
    self.typegraph = ford.graphs.TypeGraph(self.types,self.webdir,'type~~graph')
  File "/home/dix/code/python/ford/ford/graphs.py", line 449, in __init__
    self.warn = next(iter(root)).settings['warn'].lower() == 'true'
StopIteration
```

Ignoring the last line makes the build process freeze.

**Comment by haraldkl** [comment]
I would guess that `self.types` is an empty list. Do you have any derived types defined in your project?

**Comment by vdikan** [comment]
Yes, some derived types are defined.

**Comment by haraldkl** [comment]
OK, then I am not sure, why it fails. To deal with empty lists, I believe we need something like the following diff:

    --- a/ford/graphs.py    Tue Jan 09 11:46:54 2018 +0100
    +++ b/ford/graphs.py    Thu Mar 29 15:34:54 2018 +0200
    @@ -456,7 +456,10 @@
                                      eval(root.meta['graph_maxnodes']))
                 self.warn = root.settings['warn'].lower() == 'true'
             else:
    -            self.warn = next(iter(root)).settings['warn'].lower() == 'true'
    +            try:
    +                self.warn = next(iter(root)).settings['warn'].lower() == 'true'
    +            except StopIteration:
    +                pass
             self.webdir = webdir
             if ident:
                 self.ident = ident + '~~' + self.__class__.__name__

**Comment by vdikan** [comment]
@haraldkl Thank you very much! Problem solved.

You see, the project for which I began using FORD has quite a history and is rather huge. So I started from the key modules (representing core functionality), symlinking them to a separate dir and telling FORD it's the project root. 

To turn on the graphs I had to link also the modules with the imported derived types' definition.
