### ISSUE TITLE
Problem on running FORD

### ISSUE THREAD

**Issue by lifei07** [cmacmackin/ford#236]
Hi! I'm a beginner of using FORD and python. I have python 2.7 installed on Ubuntu 16.04 system and installed all the required packages (using pip method). But when I tried to test FORD on the example project file `example-project-file.md`, the error below appeared:
```
Traceback (most recent call last):
  File "/usr/local/bin/ford", line 11, in <module>
    load_entry_point('FORD==5.0.6', 'console_scripts', 'ford')()
  File "/usr/local/lib/python2.7/dist-packages/ford/__init__.py", line 351, in run
    proj_data, proj_docs, md = initialize()
  File "/usr/local/lib/python2.7/dist-packages/ford/__init__.py", line 120, in initialize
    md.convert(proj_docs)
  File "/usr/local/lib/python2.7/dist-packages/markdown/__init__.py", line 375, in convert
    newRoot = treeprocessor.run(root)
  File "/usr/local/lib/python2.7/dist-packages/markdown/treeprocessors.py", line 313, in run
    self.__build_ancestors(currElement, self.ancestors)
  File "/usr/local/lib/python2.7/dist-packages/markdown/treeprocessors.py", line 277, in __build_ancestors
    ancestors.append(parent.tag.lower())
AttributeError: 'NoneType' object has no attribute 'lower'
```
I don't know whether it is an issue of my system or just I mistook something. Looking forward to your help.

Thanks,
Fei

**Comment by lifei07** [comment]
Yes, I can. But in this way, do I have to manually re-installed all the dependencies?

**Comment by haraldkl** [comment]
No, that shouldn't be necessary.

**Comment by haraldkl** [comment]
You can still use setup.py to install the package.

**Comment by lifei07** [comment]
Thanks, I'll try that. BTW, is the recent package compatible with python 3.5 or later version?

**Comment by lifei07** [comment]
I have already had FORD run! It seems FORD cannot be installed with my default python 3.5, so I switch to python 2.7 and use pip to install FORD and all its dependencies. Then I uninstalled FORD using
```
sudo pip uninstall ford
```
and re-installed
```
sudo python setup.py install
```
It seems working normally right now. Thanks so much! @haraldkl

**Comment by zbeekman** [comment]
If this is resolved can the issue be closed?
