### ISSUE TITLE
Support for other variable types

### ISSUE THREAD

**Issue by acroucher** [cmacmackin/ford#27]
I've run into a problem when using FORD to document code that uses a library which introduces other variable types, and these are not recognised by FORD.

Specifically I'm using the [PETSc](http://www.mcs.anl.gov/petsc/) library, which is written in C, but provides interfaces so you can use it from Fortran. In your code you put in preprocessor `#include` statements to get access to the variable types and routines you need (for parallel vectors, matrices, linear and nonlinear solvers, etc.) When you declare variables of these new types, you don't use e.g. `type(Vec) :: v`, you just declare `Vec :: v`. Which is why FORD doesn't pick them up. Instead it either ignores them, or sometimes comes up with an "Invalid variable declaration" error.

It looks like FORD has a couple of regexps in **sourceform.py** that detect variable types: `VAR_TYPE_RE`, and `VARIABLE_RE` (the latter in the `FortranContainer` class). These appear to hard-code the variable types that are recognised.

Do you think it would be possible to add an option in the project file so that users could declare additional variable types they are using? These could then be added to those regexps in sourceform.py.

I realise you are busy just now, Chris, but wondered if you thought this idea has any merit, in which case I could perhaps look at working on it myself.

**Comment by szaghi** [comment]
I agree with acroucher, this can be helpful for fortran-c mixing programs. However, one of the characteristic of Ford that I love is its KISS nature: it is designed for fortran, for fortran poor man. I think this is the reason why Ford is presently better than doxygen. I am afraid that try to supporting also C Ford will become a poor brother of doxygen... I think that the suggestion of acroucher is the best way for improve Ford without losing its KISSness: let the user to define additional regexs. But I prefer that Ford hard-core remains compliant with the Fortran standard.

This is only my modest opinion, my best regards,
Stefano

**Comment by acroucher** [comment]
Totally agree Stefano, I wasn't suggesting full C support in FORD, and I have no desire for FORD to try and become doxygen. The code I'm wanting to use FORD on isn't even mixed-language- it's all in fortran, it just links to a library that's written in C. If we could just allow the user to use other variable types I think that would be enough for my purposes.

**Comment by cmacmackin** [comment]
I will certainly look at doing this at some point. Unfortunately, given what my schedule is like, I probably won't be able to devote any time to it until April (or even later). What I don't understand is how you can get away with something like `Vec :: v`. I don't see how an include statement can get a Fortran compiler to recognize that syntax. Are they doing some _very_ clever stuff with the precompiler?

**Comment by acroucher** [comment]
I'm not sure how it's done inside the library, but yes, that is the sort of syntax you use with PETSc.

**Comment by zbeekman** [comment]
I don’t think that it’s include statements doing that, it’s other preprocessor statements like `#define Var type(var)` or some other macro expansion…

**Comment by szaghi** [comment]
Sure, this is a sort of preprocessing stuff, it is not a pure C definition.

see you soon

Il giorno 02:25 gio 12/feb/2015 Izaak Beekman <notifications@github.com> ha
scritto:

**Comment by cmacmackin** [comment]
Added this feature. See [the wiki](https://github.com/cmacmackin/ford/wiki/Project-File-Options#extra_vartypes) for documentation. The changes are reflected in the current GitHub version of the code but are not yet in PyPI. They will be shortly--I just have to decide whether to implement another new feature before I make a new release.

**Comment by cmacmackin** [comment]
Those changes are now available on PyPI.
