### ISSUE TITLE
Typo in FortranSubroutine._initialize()?

### ISSUE THREAD

**Issue by acroucher** [cmacmackin/ford#28]
I just spotted something that looks like a small bug in sourceform.py. In FortranSubroutine._initialize(), line 525 says:

`if attribstr.find("elemntal") >= 0:`

Looks like a typo in "elemental"- should probably be `if attribstr.find("elemental") >= 0:` ?

**Comment by acroucher** [comment]
Oh, actually, same thing on line 599 of sourceform.py, in FortranFunction._initialize().

**Comment by cmacmackin** [comment]
Fixed that and pushed it to Github. I won't be creating a new release just for it, though. If you catch a few more bugs, then I might!
