### ISSUE TITLE
erroneous errors if output_dir string part matches project_dir

### ISSUE THREAD

**Issue by dannyk96** [cmacmackin/ford#33]
This snippet gives the following error.
~
$ head -2 danfe.md
project_dir: ./danfe
output_dir: ./danfe_doc
$ ford/ford.py -ef danfe.md
Error: output directory a subdirectory of directory containing source-code.
~~~

Note that I found a workaround by adding a '/' to the end of project_dir however I should not have to do this

**Comment by cmacmackin** [comment]
Fixed. I'll be pushing the updates to GitHub shortly.

On 24/04/15 04:16 AM, Daniel Kidger wrote:
>
> This snippet gives the following error.
> ~
> $ head -2 danfe.md
> project_dir: ./danfe
> output_dir: ./danfe_doc
> $ ford/ford.py -ef danfe.md
> Error: output directory a subdirectory of directory containing 
> source-code.
>
> |
> Note that I found a workaround by adding a '/' to the end of project_dir however I should not have to do this
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/33>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>
