### ISSUE TITLE
Request support for multiple project_dir's

### ISSUE THREAD

**Issue by dannyk96** [cmacmackin/ford#34]
My application suite keeps its source in src/ and also /libsrc.
I would like the documentation to go in doc/
However ford only allows one project_dir value and gives the error
~~~
Error: output directory a subdirectory of directory containing source-code
~~~`
if I put doc/ as the output_dir

Is there a suggested fix or workaround perhaps by using --exclude?

**Comment by cmacmackin** [comment]
Added this ability. You can now either list multiple directory names 
after the -d option on the command line or list multiple directories 
(each on their own line, as described in the documentation) in the 
project file. These changes (along with those I've mentioned in your 
other bug reports) have now been pushed to GitHub.

On 24/04/15 04:19 AM, Daniel Kidger wrote:
>
> My application suite keeps its source in src/ and also /libsrc.
> I would like the documentation to go in doc/
> However ford only allows one project_dir value and gives the error
>
> |Error: output directory a subdirectory of directory containing source-code
> ~~~`
> if I put doc/ as the output_dir
>
> Is there a suggested fix or workaround perhaps by using --exclude?
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/34>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>
