### ISSUE TITLE
Alternate syntax for indicating documentation

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#38]
Maybe include an alternate way to specify a documentation block (predocmark or docmark) by defining a docmark that indicates that the documentation is starting, and will continue until the comment block ends.  That way you don't have to include the docmark on every line, just the first one.  Example (say, let ```predocmark_alt=#```):

```fortran
!#
!  This is an example. 
!  Here is another line of comments.
!  
!  History
! ----------
!  * 1/1/2000 Created

subroutine blah()

end subroutine blah
```

What do you think? I think it makes the source look cleaner.

**Comment by cmacmackin** [comment]
This has now been added. See the [Wiki page](https://github.com/cmacmackin/ford/wiki/Project-File-Options) for details. Note that the !# line does count as the first line of documentation, which is significant if you are including any meta-data.
