### ISSUE TITLE
custom doc mark trigger (!!): feature request

### ISSUE THREAD

**Issue by szaghi** [cmacmackin/ford#4]
Hi Chris,

Into your doc I read that Ford is triggered by !! mark. It is very useful to have the possibility to customize this marker, e.g. for coders that are using doxygen: tipically the variables docstrings are triggered by !< marker.  If the Ford docstrings marker becomes customizabile the modification necessary for "old" projects are strongly reduced.

See you soon

**Comment by cmacmackin** [comment]
Ah, finally something easy! Yes, I should be able to modify the program to accept an arbitrary documentation marker. I'll probably get to that tonight.

**Comment by cmacmackin** [comment]
This feature is now available in the code. Just specify ``docmark: <`` (or whatever your preference is) in the project file.
