### ISSUE TITLE
|media| expansion in documentation of functions/subroutines

### ISSUE THREAD

**Issue by hornekyle** [cmacmackin/ford#40]
|media| does not seem to be correctly expanded in the documentation of subroutines and functions, but would be very useful for some applications.

**Comment by cmacmackin** [comment]
I've fixed this and will be pushing it to GitHub shortly. Once I've dealt with Jacob William's issues I'll author a new release for PyPI.

**Comment by hornekyle** [comment]
Thanks for looking into it. It will make ford even more useful.
