### ISSUE TITLE
predocmark_alt bug?

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#42]
I've noticed that the header from a ```predocmark_alt``` block doesn't show up if there is a blank line between the last comment at the item that is being documented.  The normal ```predocmark``` doesn't have this issue.  Example:

```predocmark_alt: >```

```Fortran
!> blah blah
!  This one doesn't work

module blah
end module blah
```

```Fortran
!> blah blah
!  This one works
module blah
end module blah
```

**Comment by cmacmackin** [comment]
Sorry about that. The alt docmarks turned out to be a real headache to 
implement and I must have made an error somewhere. I'll try to fix that 
today.

On 16/06/15 11:25 AM, Jacob Williams wrote:
>
> I've noticed that the header from a |predocmark_alt| block doesn't 
> show up if there is a blank line between the last comment at the item 
> that is being documented. The normal |predocmark| doesn't have this 
> issue. Example:
>
> |predocmark_alt: >|
>
> !> blah blah
> !  This one doesn't work
>
> module  blah
> end module  blah
> !> blah blah
> !  This one works
> module  blah
> end module  blah
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/42>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by cmacmackin** [comment]
It's fixed now. Although that whole module has become quite kludgey--I should probably reimplement it at some point.

**Comment by cmacmackin** [comment]
Oh and, incidentally, the GitHub version of FORD no longer has the restriction that a docmark must not contain any regex syntax. So you could use `!*`, for example, if you prefer.

**Comment by jacobwilliams** [comment]
Thanks!
