### ISSUE TITLE
exclude directories?

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#43]
It is possible to expand ```exclude``` to be able to specify directories that are to be excluded?

**Comment by cmacmackin** [comment]
At present, no. However, it should be trivially easy to add that. Where I've literally just created a new release, I wasn't really intending to create another one right away though.

**Comment by jacobwilliams** [comment]
Ha ha! That's fine. I just add these tickets as I think of them. No rush.

**Comment by cmacmackin** [comment]
This feature has been implemented in the latest release.
