### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#46]
Ford doesn't work properly on Windows. It is probably due to the directory slash, since it is generating a bunch of files like ```doc%5Cmodule%5Cblah.html``` rather than ```doc/module/blah.html```.  If this isn't a priority for you, I can probably take a look at it.

**Comment by cmacmackin** [comment]
Sorry about that. Looking back, I was inconsistent about these things--in some places I used the proper os.path.join while in others I was lazy and just assumed a Unix-like system. I'll try to get to this sometime today.

**Comment by cmacmackin** [comment]
I just pushed changes to GitHub which should make it work on Windows. That being said, I don't actually have a Windows machine to test it on, so I'd appreciate it if you tried it out before I release it.

**Comment by jacobwilliams** [comment]
Seems to work great! Thanks!
