### ISSUE TITLE
author metadata

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#47]
The ```author``` metadata is doing something odd. Example:
```fortran
!*****************************************************************************************
!> author: blah
!
!  blah blah.
    subroutine blah()

    end subroutine blah
!*****************************************************************************************
```
For 
```markdown
predocmark_alt: >
```

The output page looks like this:

![blah](https://cloud.githubusercontent.com/assets/6483379/8393791/fe9676ac-1ce4-11e5-8961-41d272c3a902.png)

(I'm using the latest PyPi version).

**Comment by cmacmackin** [comment]
This is fixed on the latest PyPI release. Note that FORD will now complain if you use
```
predocmark_alt: >
```
unless you also include the line
```
predocmark_alt: <something else>
```
This is because `>` is the default predocmark. FORD was meant to complain about this with v3.0.0, but I'd forgotten to add the code to check for that.

**Comment by cmacmackin** [comment]
Also, be aware that `*` is the default docmark_alt now. As such, in the code snippet you gave, the source file's documentation contained two lines of asterisks, which Markdown interprets as <hr>. You might want to turn that off by putting
```
docmark_alt: 
```
in the project file meta-data.

**Comment by jacobwilliams** [comment]
Works great! Thanks!
