### ISSUE TITLE
Badges not correctly rendering

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#48]
I’m just curious if you know what’s going on with some of the badges not rendering correctly when included in FORD documentation. For example take a look here: http://szaghi.github.io/FLAP/index.html in the compiler support section, vs when rendered by github: https://github.com/szaghi/FLAP/blob/master/README.md

Is it the `+` characters throwing off the markdown renderer? Is this due to FORD or the vendor/upstream markdown rendering FORD uses?

**Comment by zbeekman** [comment]
I determined the issue: Adding parenthesis inside markdown image urls (and possibly link urls) causes the markdown output to be different than github’s rendering. Whether this is legal markdown (having parens in urls) or not, I have no idea. I’m going to go ahead and close this issue unless you, @cmacmackin, think that this is worth trying to address.

**Comment by cmacmackin** [comment]
Thanks for drawing this to my attention. I have no idea if this is legal markdown. To be honest, I don't think Markdown really has an official standard, other than what was published [here](http://daringfireball.net/projects/markdown/syntax). Having looked at that, it doesn't say anything one way or the other about how Markdown should treat parentheses within links and images. Clearly Python-Markdown and GitHub-Flavoured-Markdown treat it differently. I don't really think there is anything I'd want to do about this. However, you (and @szhagi) might be able to get around the problem by using "reference links" (see the documentation linked to above).

**Comment by zbeekman** [comment]
oh, cool, I wasn’t aware of reference links. I actually just ended up removing the parentheses from the link text so that it can be consistent across the GFM and FORD markdown, and I think it looks cleaner.
