### ISSUE TITLE
Non-Fortran source files

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#52]
One thing that might be handy would be to have the ability to include non-Fortran source files in the documentation. Some ideas:
 * They would not be parsed, but would be included in the list of source files.
 * If they were a known source code format (say, C), then they could also be syntax highlighted.
 * Include the ability to have a source file level documentation block (one that applies to the file itself, rather than to a specific variable or procedure).  It would appear at the top of the source file page, and be parsed as Markdown, etc. like normal. This may also be handy for normal Fortran files (or say, an old school .for file that is just a bunch of subroutines).  For non-Fortran files, it would have to account for the different comment characters in the different languages.

What do you think? This is probably a longer-term feature, but I think it would be quite handy. I have several use cases for this (e.g., a shell script that goes with a program, or a C-header file that defines the C-bindings to the Fortran code, etc.).

**Comment by cmacmackin** [comment]
Yeah, as a longer-term goal this is doable--at least for a subset of 
languages. The trickiest part would be to get Ford to recognize what is 
documentation.

By the way, source file level documentation blocks already exist for 
FORD. Just use the docmark (or docmark_alt) somewhere in your source 
file that is outside of any module, program, or procedure.

On 01/07/15 11:30 PM, Jacob Williams wrote:
>
> One thing that might be handy would be to have the ability to include 
> non-Fortran source files in the documentation. Some ideas:
>
>   * They would not be parsed, but would be included in the list of
>     source files.
>   * If they were a known source code format (say, C), then they could
>     also be syntax highlighted.
>   * Include the ability to have a source file level documentation
>     block (one that applies to the file itself, rather than to a
>     specific variable or procedure). It would appear at the top of the
>     source file page, and be parsed as Markdown, etc. like normal.
>     This may also be handy for normal Fortran files (or say, an old
>     school .for file that is just a bunch of subroutines). For
>     non-Fortran files, it would have to account for the different
>     comment characters in the different languages.
>
> What do you think? This is probably a longer-term feature, but I think 
> it would be quite handy. I have several use cases for this (e.g., a 
> shell script that goes with a program, or a C-header file that defines 
> the C-bindings to the Fortran code, etc.).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/52>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by cmacmackin** [comment]
This is supported as of v4.5.0. See the [wiki](https://github.com/cmacmackin/ford/wiki/Writing-Documentation#non-fortran-source-files).

**Comment by zbeekman** [comment]
:bow: AMAZING!
