### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#53]
Unless you object, @cmacmackin, I’m going to use [homebrew-pypi-poet](https://github.com/tdsmith/homebrew-pypi-poet) to submit a Formula for FORD to Homebrew. This will then allow us to use it as 

```ruby
depends_on "FORD" => [:recommended, :build]
```

in our `json-fortran.rb` formula when we migrate the master branch to FORD documentation and tag the next release.

CC: @jacobwilliams

**Comment by cmacmackin** [comment]
Sounds good!

On 02/07/15 02:06 PM, Izaak Beekman wrote:
>
> Unless you object I’m going to use homebrew-pypi-poet 
> <https://github.com/tdsmith/homebrew-pypi-poet> to submit a Formula 
> for FORD to Homebrew. This will then allow us to use it as
>
> depends_on"FORD"  => [:recommended,:build]
>
> in our |json-fortran.rb| formula when we migrate the master branch to 
> FORD documentation and tag the next release.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/53>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by zbeekman** [comment]
good, because I actually just submitted a [PR](https://github.com/Homebrew/homebrew/pull/41296) over at Homebrew

**Comment by zbeekman** [comment]
Home-brew has just accepted the FORD formula PR. To install via home-brew:
```bash
$ brew update
$ brew info FORD
$ brew install FORD
```

(Or `brew install --HEAD FORD` to install directly from the github master branch)

**Comment by cmacmackin** [comment]
Glad to hear it!
