### ISSUE TITLE
modification times

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#55]
This may be a complete non-issue/won’t fix in your opinion, which I’m fine with but I just wanted to document it, and let you decide what you think.

It seems that the modifications times in some of the subfolders are not updated when FORD generates documentation. Depending on how the build system is set up this can cause tools like `make` to think that the documentation is out of date relative to the input files. Due to the slow processing time, #16, this is undesirable, because this in turn causes the documentation to be rebuilt always. It could be nice if FORD `touch`ed the contents of the following output directories each time it generates documentation:
 * `css`
 * `js` 
 * `fonts`
 * `tipuesearch`

Using CMake I run FORD during  configuration to determine what files are produced, and currently need to limit the glob I use for this to `*.html` because the fonts/css/js files are copied into the `doc` output folder with modification times from back in December and January. This means that I then have to do extra work to tell CMake to delete these other files too, when executing the clean rule.

**Comment by cmacmackin** [comment]
I find it really strange that you are experiencing this problem, because 
FORD deletes and then recopies all of those files every time it runs. I 
don't know what to make of this.

On 06/07/15 07:07 PM, Izaak Beekman wrote:
>
> This may be a complete non-issue/won’t fix in your opinion, which I’m 
> fine with but I just wanted to document it, and let you decide what 
> you think.
>
> It seems that the modifications times in some of the subfolders are 
> not updated when FORD generates documentation. Depending on how the 
> build system is set up this can cause tools like |make| to think that 
> the documentation is out of date relative to the input files. Due to 
> the slow processing time, #16 
> <https://github.com/cmacmackin/ford/issues/16>, this is undesirable, 
> because this in turn causes the documentation to be rebuilt always. It 
> could be nice if FORD |touch|ed the contents of the following output 
> directories each time it generates documentation:
>
>   * |css|
>   * |js|
>   * |fonts|
>   * |tipuesearch|
>
> Using CMake I run FORD during configuration to determine what files 
> are produced, and currently need to limit the glob I use for this to 
> |*.html| because the fonts/css/js files are copied into the |doc| 
> output folder with modification times from back in December and 
> January. This means that I then have to do extra work to tell CMake to 
> delete these other files too, when executing the clean rule.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/55>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by zbeekman** [comment]
I think the issue is that it copies the files but the modification times are preserved when it copies them. The last time the files were modified was when the maintainers of bootstrap touched them, it would appear. FWIW this is on Mac OS X. Different filesystems may behave differently in terms of preserving modification times.

**Comment by cmacmackin** [comment]
Fixed with the latest update.
