### ISSUE TITLE
pages subdirectories attempted copy as file

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#58]
I’m getting the following warnings running FORD:

```
Warning: could not copy file pages/1.0.0. Error: 21
Warning: could not copy file pages/2.0.0. Error: 21
Warning: could not copy file pages/3.0.0. Error: 21
Warning: could not copy file pages/3.1.0. Error: 21
Warning: could not copy file pages/4.0.0. Error: 21
Warning: could not copy file pages/4.1.0. Error: 21
Warning: could not copy file pages/4.1.1. Error: 21
```

Each subdirectory has an index.md file in it. Should I change the naming convention of the pages subdirectories so that they don’t have periods in them or is this a FORD bug?

**Comment by cmacmackin** [comment]
I'm pretty sure this is a bug, but without knowing some details of your 
directory structure it is hard to say. Could you post that, in a 
simplified form if you prefer?

On 08/07/15 01:51 PM, Izaak Beekman wrote:
>
> I’m getting the following warnings running FORD:
>
> |Warning: could not copy file pages/1.0.0. Error: 21
> Warning: could not copy file pages/2.0.0. Error: 21
> Warning: could not copy file pages/3.0.0. Error: 21
> Warning: could not copy file pages/3.1.0. Error: 21
> Warning: could not copy file pages/4.0.0. Error: 21
> Warning: could not copy file pages/4.1.0. Error: 21
> Warning: could not copy file pages/4.1.1. Error: 21
> |
>
> Each subdirectory has an index.md file in it. Should I change the 
> naming convention of the pages subdirectories so that they don’t have 
> periods in them or is this a FORD bug?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/58>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by zbeekman** [comment]
I’m seeing this in other cases too… Here is an example:

```
$ ford -p pages/4.1.1 json-fortran.md
Reading file src/json_module.F90

Correlating information from different parts of your project...

Reading page pages/4.1.1/index.md

Creating HTML documentation...
Warning: could not copy file pages/4.1.1/tests. Error: 21
```

```
$ tree pages/4.1.1/
pages/4.1.1/
├── index.md
├── index.md~
├── json_module_F90.html
├── masterindex.html
├── robo_classes.html
├── robo_definitions.html
├── robo_functions.html
├── robo_interfaces.html
├── robo_macros.html
├── robo_modules.html
├── robo_sourcefiles.html
├── robo_unittests.html
├── robodoc.css
└── tests
    ├── index.md
    ├── introspection
    │   ├── index.md
    │   └── test_iso_10646_support_f90.html
    ├── jf_test_10_f90.html
    ├── jf_test_11_F90.html
    ├── jf_test_1_f90.html
    ├── jf_test_2_f90.html
    ├── jf_test_3_f90.html
    ├── jf_test_4_f90.html
    ├── jf_test_5_f90.html
    ├── jf_test_6_f90.html
    ├── jf_test_7_f90.html
    ├── jf_test_8_f90.html
    └── jf_test_9_f90.html

2 directories, 27 files
```

**Comment by cmacmackin** [comment]
Okay, I'm pretty sure I know the source of the bug. I'll fix it and put 
out a new release this evening.

On 08/07/15 02:04 PM, Izaak Beekman wrote:
>
> I’m seeing this in other cases too… Here is an example:
>
> |$ ford -p pages/4.1.1 json-fortran.md
> Reading file src/json_module.F90
>
> Correlating information from different parts of your project...
>
> Reading page pages/4.1.1/index.md
>
> Creating HTML documentation...
> Warning: could not copy file pages/4.1.1/tests. Error: 21
> |
> |$ tree pages/4.1.1/
> pages/4.1.1/
> ├── index.md
> ├── index.md~
> ├── json_module_F90.html
> ├── masterindex.html
> ├── robo_classes.html
> ├── robo_definitions.html
> ├── robo_functions.html
> ├── robo_interfaces.html
> ├── robo_macros.html
> ├── robo_modules.html
> ├── robo_sourcefiles.html
> ├── robo_unittests.html
> ├── robodoc.css
> └── tests
>      ├── index.md
>      ├── introspection
>      │   ├── index.md
>      │   └── test_iso_10646_support_f90.html
>      ├── jf_test_10_f90.html
>      ├── jf_test_11_F90.html
>      ├── jf_test_1_f90.html
>      ├── jf_test_2_f90.html
>      ├── jf_test_3_f90.html
>      ├── jf_test_4_f90.html
>      ├── jf_test_5_f90.html
>      ├── jf_test_6_f90.html
>      ├── jf_test_7_f90.html
>      ├── jf_test_8_f90.html
>      └── jf_test_9_f90.html
>
> 2 directories, 27 files
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/58#issuecomment-119664161>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by cmacmackin** [comment]
Fixed with the latest update.
