### ISSUE TITLE
private derived type documentation missing

### ISSUE THREAD

**Issue by szaghi** [cmacmackin/ford#6]
Hi Chris,

I am playing with ford and I like it more and more.

At this page http://szaghi.github.io/FLAP/module/data_type_command_line_interface.html you can find the doc of **Type_Command_Line_Interface** derived type. As you can see it has a component defined as **Type_Command_Line_Argument** which is hyper-linked to its own doc page. However, the doc page of **Type_Command_Line_Argument** is missing. 

I guess that is due to the **private** attribute  of the **Type_Command_Line_Argument** derived type. Is it true? 

Is it a bug or a design behavior? In this case, is it possible to create documentation of also private entities?

See you soon.

**Comment by cmacmackin** [comment]
Yes, that is the reason why no documentation was created for Type_Command_Line_Argument. I hadn't anticipated that there would be a variable with a private derived type which is publicly accessible. I don't particularly want to change FORD's behaviour by making documentation for a private type and it would be difficult to over-ride it in a specific case like this one. I think I'll just add some logic to remove the hyperlink. If that is unsatisfactory then I can perhaps increase the priority of adding the ability to be able to force something to be documented even if it private.

**Comment by szaghi** [comment]
Hi Chris,

thank you very much for work!

I do not like to impose my preference. I like to document everything, but it is not a priority. I think that you should follow your preferences...

**Comment by cmacmackin** [comment]
Well, if you'd like to document everything, then just add the following 
lines to the meta-data in your project file:
````
display: public
          protected
          private
````

On 07/01/15 10:59 AM, Stefano Zaghi wrote:
>
> Hi Chris,
>
> thank you very much for work!
>
> I do not like to impose my preference. I like to document everything, 
> but it is not a priority. I think that you should follow your 
> preferences...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/6#issuecomment-69032725>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by szaghi** [comment]
Great!
