### ISSUE TITLE
markdown.extensions.abbr issues

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#60]
This is pretty minor, and I’d be content if you said this was a “won’t fix” or if the issue is upstream, but using the `md_extensions: markdown.extensions.abbr` in the project file and then declaring an abbreviation causes spurious characters to be printed below the top menu bar but above the page content:
![screen shot 2015-07-09 at 6 27 27 pm](https://cloud.githubusercontent.com/assets/279612/8608390/84349852-2668-11e5-9ea0-598aaa0a2e65.png)

**Comment by cmacmackin** [comment]
Hmm... I can't seem to reproduce this. However, you shouldn't actually need to specify `md_extensions: markdown.extensions.abbr` in the project file, as `markdown.extensions` is loaded by default. The error may have something to do with `markdown.extensions.abbr` effectively being loaded twice.

**Comment by zbeekman** [comment]
Thanks for looking into it. I ran some more tests and it only happens when I add a definition of a word/term/abbreviation that appears in the `summary: …` meta data. In the above example I was trying to add `*[API]: Application programmable interface` and/or `*[JSON]: JavaScript Object Notation` as definitions to the main [json-fortran.md](https://github.com/jacobwilliams/json-fortran/blob/master/json-fortran.md) project file.

**Comment by cmacmackin** [comment]
Fixed it. The summary is placed in HTML metadata and the quotation marks in the abbrv tags were causing problems. Those tags will now be stripped out of the version of the summary placed in the metadata. The fix will be released shortly.
