### ISSUE TITLE
warning when running FORD on Travis-CI

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#61]
See [here](https://travis-ci.org/jacobwilliams/json-fortran/jobs/70979354#L794) for more details. It looks like BeautifulSoup wants you to specify an HTML parser. Not an issue for me, but just want to make you aware of it.

**Comment by cmacmackin** [comment]
Fixed (I think). If, once the update is released, Travis CI still gives this warning, let me know.
