### ISSUE TITLE
overloaded interfaces tab?

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#62]
It would be nice to have a list of overloaded interfaces too, in addition to modules, procedures, derived types, etc. because these are often the ones you care about most, and are intended for consumption by client code.

P.S. Haven’t seen any activity in a while from you, I hope you’re well and on vacation or something fun like that! Please don’t feel you need to respond before you get back, if that is the case.

**Comment by cmacmackin** [comment]
Hmm... That wasn't really the way I was thinking of organizing it. I'll 
have to think this one over. I've mostly just been busy lately and also 
I needed a break from FORD. I'm hoping to get through some of the bug 
reports and feature requests this week.

On 17/07/15 12:54 PM, Izaak Beekman wrote:
>
> It would be nice to have a list of overloaded interfaces too, in 
> addition to modules, procedures, derived types, etc. because these are 
> often the ones you care about most, and are intended for consumption 
> by client code.
>
> P.S. Haven’t seen any activity in a while from you, I hope you’re well 
> and on vacation or something fun like that! Please don’t feel you need 
> to respond before you get back, if that is the case.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/62>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by zbeekman** [comment]
I think you're right and my approach is not well developed. What I'm really after is some way to separate internal procedures and entities from those that are publicly accessible through `use` statements. (I know you have options to include or exclude private entities.) Maybe the new sorting functionality you just added help in this regard, but I just got back from the wilderness and have yet to try it.

**Comment by cmacmackin** [comment]
Well, the original intention was that you would run FORD with private entities hidden if you wanted to emphasize the public API. I don't think that the new sort features will be too helpful in this regard, as the list pages are still sorted alphabetically. One way you could emphasize the public entities would be to manually list them on the homepage using the [internal link syntax](https://github.com/cmacmackin/ford/wiki/Writing-Documentation#links).

**Comment by zbeekman** [comment]
Yeah, that’s fine. The visibility hiding is good enough.
