### ISSUE TITLE
argument order in documentation different than source

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#64]
The argument list given in the documentation is in a different order than the dummy arguments are written in the source code. This is important since, a lot of the time actual arguments are given positionally and not with keyword calls.

**Comment by cmacmackin** [comment]
Ah, this is a side-effect of how I approached the sort-ordering. For now 
the work-araound is to turn it off. I'll get a proper fix for that out soon.

On 23/07/15 10:43 AM, Izaak Beekman wrote:
>
> The argument list given in the documentation is in a different order 
> than the dummy arguments are written in the source code. This is 
> important since, a lot of the time actual arguments are given 
> positionally and not with keyword calls.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/64>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by cmacmackin** [comment]
I've fixed this so that the arguments are listed in the correct order next to the procedure name. At the moment the actual table of arguments is still being sorted like other variables (so it could be alphabetical, variable type, intent...). I'm not sure whether it might be better just to keep the arguments in the same order they occur in the argument list, though. Thoughts?

**Comment by zbeekman** [comment]
The critical issue IMO is to make sure that the arguments appearing next to the procedure are listed in the same order as the source. The ordering of the argument table is less important, since in the source the order in which you declare arguments need not be the same as the order in which they appear in the argument list.

However, I *really* like your idea of presenting them in the table in the same order as they appear in the source and documentation argument list.

**Comment by zbeekman** [comment]
Should we close this since its fixed or are you still contemplating what to do about the argument order in the table?

**Comment by cmacmackin** [comment]
I have fixed it. I was planning to close the issue once I've gotten a 
new release pushed out. I was hoping that would be done by now, but I 
want to implement submodules and hadn't realized quite how big a job 
that will be.

On 05/08/15 11:51 AM, Izaak Beekman wrote:
>
> Should we close this since its fixed or are you still contemplating 
> what to do about the argument order in the table?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/64#issuecomment-128023325>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by zbeekman** [comment]
OK… just curious what your estimated time frame is for the next release… I have yet to update the Homebrew Formula for v4.0.1 (last is 4.0.0) and was thinking I might just wait until you publish the next release.

**Comment by cmacmackin** [comment]
Hopefully no more than a week. You might as well wait.

On 05/08/15 11:56 AM, Izaak Beekman wrote:
>
> OK… just curious what your estimated time frame is for the next 
> release… I have yet to update the Homebrew Formula for v4.0.1 (last is 
> 4.0.0) and was thinking I might just wait until you publish the next 
> release.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/64#issuecomment-128025453>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by zbeekman** [comment]
OK, thanks!
