### ISSUE TITLE
-p flag not overriding page_dir:

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#65]
Hi Chris,
When I call ford from the command line with the `-p` flag (as part of an out of source CMake build process) the `page_dir:` meta data is still being used from the project file.

**Comment by cmacmackin** [comment]
I'm not able to reproduce this.

**Comment by zbeekman** [comment]
hmmmm well it turns out that it’s actually easier for me to not include this in the project file at all… so it’s no longer an issue for me. I may mess around a bit and see if I can create a simple reproducer, but I’m running out of time today.

**Comment by zbeekman** [comment]
I’m going to close this, because we are now always passing the `page_dir` via the `-p` flag and have removed it from the project file. There may be a lingering bug, but, since you can’t reproduce it, and it no longer effects us, I’m going to close this issue.
