### ISSUE TITLE
better anchor name mangling

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#66]
Often overloaded procedures will have many specific procedures who use the same dummy argument name. In the interface documentation, ford creates many anchors with the same `name` attribute for these dummy variables.

This has not caused any issues for me, other than complaints from the [W3C Link Checker](https://validator.w3.org/checklink?uri=http%3A%2F%2Fjacobwilliams.github.io%2Fjson-fortran%2Finterface%2Fjson_add.html&hide_type=all&depth=&check=Check) so it may not be the type of thing that actually needs to be fixed. However, in general, there may be instances where better name mangling is needed. Something like `file_name-module_name-procedure_name-var_name` could help disambiguate entities.

I don’t know whether or not this is something that should be changed/fixed.

**Comment by cmacmackin** [comment]
I don't know if this would actually have caused any problems, but I've fixed it anyway.
