### ISSUE TITLE
Links for `interface operator(…)` do not properly resolve to corresponding page

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#67]
I am not sure whether it is a problem with the page naming scheme when special characters exist or if it is a problem with the link generation, but links which should point to pages like `interface/operator%28slashslash%29.html` (`operator(//)`) and `interface/operator%28%3D%3D%29.html` (`operator(==)`) throw 404s.

**Comment by zbeekman** [comment]
You can see an example here: http://jacobwilliams.github.io/json-fortran/module/json_module.html#intr-operator(//)

**Comment by cmacmackin** [comment]
I've fixed this. It will be available in the next release.

**Comment by zbeekman** [comment]
Great, thanks Chris!
