### ISSUE TITLE
Not showing that a class is abstract.

### ISSUE THREAD

**Issue by cmacmackin** [cmacmackin/ford#68]
See http://jacobwilliams.github.io/bspline-fortran/module/bspline_oo_module.html#type-bspline_class for an example.

**Comment by szaghi** [comment]
also this http://fortran-foss-programmers.github.io/WenOOF/type/weno_interpolator.html

**Comment by cmacmackin** [comment]
This is now fixed and will be in the next release

**Comment by szaghi** [comment]
Great!
