### ISSUE TITLE
Problem in parsing a file

### ISSUE THREAD

**Issue by szaghi** [cmacmackin/ford#69]
Hi Chris,

I have a problem for building the documentation of WenOOF. There is a file that is not parsed by ford. If I run ford with warnings activated I obtain;

```shell
Warning: Error parsing src/lib/type_weno_interpolator_upwind.f90.
	Found variable in INTERFACE
```

I cannot understand what I missed.

You can found the source [here](https://github.com/Fortran-FOSS-Programmers/WenOOF/blob/master/src/lib/type_weno_interpolator_upwind.f90), the compilations log [here](https://travis-ci.org/Fortran-FOSS-Programmers/WenOOF) and the generated documentation [here](http://fortran-foss-programmers.github.io/WenOOF/index.html).

I suspect that is something related to the overloading of the name `weno_constructor_upwind` that is both the name of a derived type and of an interface used as *constructor*.

**Comment by cmacmackin** [comment]
This came down to my not knowing that the following was legal syntax:
```fortran
interface weno_constructor_upwind
  procedure weno_constructor_upwind_init
endinterface
```
I thought that you would need to put `module procedure weno_constructor_upwind_init`. This is fixed and will be released once I've implemented submodules.

**Comment by szaghi** [comment]
@cmacmackin This should be standard conforming (compiled with -std08 in both gfortran and intel).

It is a *standard* approach described into the Rouson's book: create an interface overloading the name of a derived type in order to provide a *constructor function* returning an initialized instance of that type.

However I do not follow your hint: it is already stated `module procedure weno_constructor_upwind_init`, what I have to put? the eventual ambiguous names are the type name and interface one, both being `weno_constructor_upwind`.

Thank you very much for your help.

**Comment by cmacmackin** [comment]
Oh, sorry, I don't mean that I was unaware of type-name overloading. To make it work, just put 
```fortran
interface weno_constructor_upwind
  module procedure weno_constructor_upwind_init
endinterface
```

**Comment by szaghi** [comment]
Ok, just see the addition of module!

Thank you very much!

**Comment by szaghi** [comment]
Works perfectly!

Thank you again!
