### ISSUE TITLE
program's doc page missing

### ISSUE THREAD

**Issue by szaghi** [cmacmackin/ford#7]
Hi Chris,

with the **FLAP** project I am using for testing **ford** I find that the doc page of a testing program (FLAP_Test) is not created, see http://szaghi.github.io/FLAP/program/FLAP_Test.html.

Is it a bug or is there a mistake in main ford's project file (https://github.com/szaghi/FLAP/blob/master/doc/main_page.md)?

See you soon.

**Comment by cmacmackin** [comment]
That was a small bug. I've fixed it and will push it to github shortly.

**Comment by szaghi** [comment]
Great!
