### ISSUE TITLE
Python 3 and source option

### ISSUE THREAD

**Issue by gebeele** [cmacmackin/ford#72]
I was trying it this evening and saw a couple of things. Maybe I did something wrong...
- Error running ford in my default python 3 
distribution. It seems it is a problem importing the stringio module
- I did not manage to hide the code by using the option source: false in the project configuration file
Very useful, by the way!
Gustavo

**Comment by cmacmackin** [comment]
I've ensured that it works with Python 3 now. There will be a new release soon. I haven't been able to replicate hiding the source. To be clear, links to the source-code and the pages for source-files are not affected by setting`source: false`. That only affects whether FORD will attempt to place syntax-highlighted source-code at the bottom of the page for procedures and derived types.

**Comment by gebeele** [comment]
Thanks. Great.
I thought about hiding private objects and source as useful for distributing precompiled libraries to users that "do not need" to have the code and methods. But I guess it would not be difficult to hide manuallly the code pages from the FORD output anyway.
