### ISSUE TITLE
Problem with trying to display everything (public, private, protected)

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#74]
Hi Chris,
I was in the process of documenting some old code, and updating it, but FORD is crashing on me when I try set the display scope to include everything: Public, protected and private entities. [Here](https://obj.umiacs.umd.edu/public-test/FAAST.tgz) is a tarball of the sources illustrating the problem. The display meta data entry is on line 6 of FAAST-meta.md. If you pick private or public it works, but if you try to include both of them it won't. (Right now just `display: private` is set.)

Here is the error message I get:
```
$ ford FAAST-meta.md
Reading file src/faast-implementation.f90

Processing documentation comments...
Correlating information from different parts of your project...

Creating HTML documentation...
Traceback (most recent call last):
  File "/usr/local/bin/ford", line 9, in <module>
    load_entry_point('FORD==4.1.0', 'console_scripts', 'ford')()
  File "/usr/local/lib/python2.7/site-packages/ford/__init__.py", line 269, in main
    process()
  File "/usr/local/lib/python2.7/site-packages/ford/__init__.py", line 261, in process
    ford.output.print_html(project,proj_data,proj_docs_,page_tree,relative)
  File "/usr/local/lib/python2.7/site-packages/ford/output.py", line 199, in print_html
    html = template.render(proj_data,dtype=dtype,project=project)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/ford/templates/type_page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/lib/python2.7/site-packages/ford/templates/base.html", line 98, in top-level template code
    {% block body %}
  File "/usr/local/lib/python2.7/site-packages/ford/templates/type_page.html", line 62, in block "body"
    {{ macros.bound_info(bp) }}
  File "/usr/local/lib/python2.7/site-packages/ford/templates/macros.html", line 375, in template
    {{ proc_summary(bind) }}
  File "/usr/local/lib/python2.7/site-packages/ford/templates/macros.html", line 319, in template
    {% if small %}<h5>{% else %}<h3>{% endif %}{{ proc_line(proc,proto=proto) }}{% if proto %}<small>Prototype</small>{% endif %}{% if small %}</h5>{% else %}</h3>{% endif %}
  File "/usr/local/lib/python2.7/site-packages/ford/templates/macros.html", line 443, in template
    {% if proc.meta['deprecated'] and proc.meta['deprecated'].lower() == 'true' %}
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 389, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'meta'
```

**Comment by zbeekman** [comment]
Also, FYI I tried to hack around at the source code to make a simpler reproducer without much luck.

**Comment by cmacmackin** [comment]
As far as I can tell, this code shouldn't compile. You've bound procedures `put_list` and `get_list` to the type `sllist`, but neither is actually defined anywhere in the code. As I state in the Wiki, it is not my policy to ensure that FORD run successfully on code that won't compile.

**Comment by zbeekman** [comment]
Sure, fair enough. Let me double check, but I think I have since remedied any issues and compiled with gfortran 5.1 but still encounter the issue. I can look in the morning.

**Comment by cmacmackin** [comment]
Have you confirmed if this problem still exists? I'm hoping to author a new release tonight and would prefer to fix this bug first.

**Comment by zbeekman** [comment]
Hey sorry I'm on vacation and didn't get to it just yet. I think I can in the next half.

**Comment by zbeekman** [comment]
*half hour

**Comment by zbeekman** [comment]
Chris, let's close this for now. I may have been erroneous in my recollection, since now--with numerous changes beyond just the addition of the missing TBPs--FORD is behaving as expected with my code. I could swear that a problem remained even after adding the missing TBPs but things are currently behaving as expected, and there many more enjoyable things to do with our time than try to prove the veracity of a questionable memory of mine. Sorry for the noise/distraction.

**Comment by zbeekman** [comment]
I can't close this on the mobile app so feel free to close it for me, or I can do it later.

**Comment by cmacmackin** [comment]
No problem. I've certainly had plenty of experiences myself where I could swear there was a problem which is gone the next time I check.

**Comment by zbeekman** [comment]
Hi Chris,
I have confirmed that the minimal set of changes required to get the software to compile no longer raises any errors when adding public, private and protected visibility. There were a few errors beyond just the lack of procedures to implement the type bound procedures.

It would be nice to have more informative error messages, or, at least a page on the wiki to help one figure out how to trace an error, but this is not an urgent priority, IMO.

Your most recent set of changes (the inclusion of a call graph) is INCREDIBLE, BTW.

**Comment by cmacmackin** [comment]
Thanks for the kind words. I hear you on the error-messages. I'll open an issue for that and see what I can do. However, I don't think I'll be developing FORD to much for a few months, as there are some other projects I want to work on and then I'll be getting settled in to grad school.
