### ISSUE TITLE
Function statement suffix required to be in particular order

### ISSUE THREAD

**Issue by pheibarrass** [cmacmackin/ford#77]
When a function statement suffix gives both a result and a binding specification, the regex parser requires that the result be given before the binding.  That is, the following fails

    module a
      interface
        function f() bind(c) result(r)
          use iso_c_binding
          integer(c_int) r
        end function f
      end interface
    end module a

with the message

> AttributeError: 'str' object has no attribute 'correlate'

while the same with

    function f() result(r) bind(c)

is accepted.

**Comment by cmacmackin** [comment]
My apologies. I had been under the impression that only the former order was allowed (I guess because that's how it is always shown in examples), but I see from the standard that this is not the case. I'll make sure to fix that for the next release.

**Comment by cmacmackin** [comment]
Fixed in [version 4.2.2](https://github.com/cmacmackin/ford/releases/tag/v4.2.2).
