### ISSUE TITLE
intrinsic routines in call graph

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#78]
Calls to the intrinsic ```character``` and ```backspace``` are showing up in the call graphs in grey boxes.  For example, in the code:
```Fortran
    allocate( character(kind=CK,len=iend-istart+1) :: line )
```
and 
```Fortran
    backspace(iunit, iostat=istat)
```

**Comment by cmacmackin** [comment]
Yeah, I was afraid of this. The only way I have to weed these out is to 
compile a list of every intrinsic routine and it is hard to find a 
comprehensive list. Please let me know if you find any more. To be 
clear, was it the `allocate` or the `character` in the first of these 
which was showing up?

On 26/08/15 10:51 PM, Jacob Williams wrote:
>
> Calls to the intrinsic |character| and |backspace| are showing up in 
> the call graphs in grey boxes. For example, in the code:
>
>      allocate(character(kind=CK,len=iend-istart+1)::  line )
>
> and
>
>      backspace(iunit, iostat=istat)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/78>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by jacobwilliams** [comment]
It's the ```character```.

FYI: [Here](https://github.com/jacobwilliams/Fortran-ROBODoc-RC-File/blob/master/robodoc.rc) is a list I compiled a while back. There references are also given.

**Comment by cmacmackin** [comment]
Those have all been added to my list.
