### ISSUE TITLE
note environment for emphasizing some docstrings: feature request

### ISSUE THREAD

**Issue by szaghi** [cmacmackin/ford#8]
Hi Chris,

One feature of doxygen I am addicted is the **@note** statement that triggers a *note environment* putting the doc-string following the maker into an emphasized box (paragraph). 

Can you add such a feature to the todo list?

See you soon.

**Comment by cmacmackin** [comment]
That shouldn't be too hard to do. I can just add a regular expression to find and replace @note (or whatever I decide to use) with the appropriate <div> tags. I'm sure Bootstrap will have a nice class to use for a note.

**Comment by cmacmackin** [comment]
Done! They should work exactly the same way as in Doxygen.

**Comment by cmacmackin** [comment]
Just a heads up! I've done something which I shouldn't have, really, as it broke the API (well, the way a user defines a setting) slightly. Previously all directors were referred to as something_dir, except for the directory containing the source code. This was referred to as project_directory. I have shortened this to project_dir so as to fit with the others. Sorry for the inconvenience, but in the long run this does make more sense.

**Comment by szaghi** [comment]
No problem. This the time to make the right choiches, the API can be
unstable in this phase.

Great job Chris, Ford rocks!

Il giorno 05:33 gio 08/gen/2015 Chris MacMackin <notifications@github.com>
ha scritto:

**Comment by cmacmackin** [comment]
Thanks! I put a lot of work into it, so it's very gratifying to know 
that other people like it.

On 08/01/15 12:51 AM, Stefano Zaghi wrote:
> No problem. This the time to make the right choiches, the API can be
> unstable in this phase.
>
> Great job Chris, Ford rocks!
>
> Il giorno 05:33 gio 08/gen/2015 Chris MacMackin 
> <notifications@github.com>
> ha scritto:
>
> > Just a heads up! I've done something which I shouldn't have, really, 
> as it
> > broke the API (well, the way a user defines a setting) slightly. 
> Previously
> > all directors were referred to as something_dir, except for the 
> directory
> > containing the source code. This was referred to as 
> project_directory. I
> > have shortened this to project_dir so as to fit with the others. 
> Sorry for
> > the inconvenience, but in the long run this does make more sense.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cmacmackin/ford/issues/8#issuecomment-69134788>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/8#issuecomment-69135705>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by szaghi** [comment]
Just tested the Note environment... beautiful! Looks very clear! Thanks.

I will aspect the **include** statement to migrate all my projects to Ford.

Thank you very much!

**Comment by cmacmackin** [comment]
The include statement is coming. I'm going to implement it as a Markdown 
extension and I just need to think about how best to do it.

On 08/01/15 03:49 AM, Stefano Zaghi wrote:
>
> Just tested the Note environment... beautiful! Looks very clear! Thanks.
>
> I will aspect the *include* statement to migrate all my projects to Ford.
>
> Thank you very much!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/8#issuecomment-69146611>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by szaghi** [comment]
Happy to read it!

One of my codes has been migrated to Ford: https://github.com/szaghi/FLAP.

I have explicitly cited ford: https://github.com/szaghi/FLAP#doc

I hope this is not  problem for you.

I will migrate OFF and Lib_VTK_IO soon.

See you soon.
