### ISSUE TITLE
Link to README from source documentation broken

### ISSUE THREAD

**Issue by hornekyle** [cmacmackin/ford#81]
When I try to navigate from a source file's documentation to the README link in the top navigation bar the path is invalid, using ., instead of .. for a relative path change.

**Comment by hornekyle** [comment]
I suspect that the problem occurs due to ford/output.py:64, which is the following:
ford.pagetree.set_base_url('.,')

Surely this should be '..'?

**Comment by hornekyle** [comment]
After patching my local copy of ford/output.py:64 from:

ford.pagetree.set_base_url('.,')

to

ford.pagetree.set_base_url('..')

the problem seems to be fixed.

**Comment by cmacmackin** [comment]
That is correct. I did a major refactoring of output.py and obviously 
made a typo. The fix will be in the next release.

On 29/08/15 02:32 PM, Kyle Horne wrote:
>
> After patching my local copy of ford/output.py:64 from:
>
> ford.pagetree.set_base_url('.,')
>
> to
>
> ford.pagetree.set_base_url('..')
>
> the problem seems to be fixed.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/81#issuecomment-136015130>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>
