### ISSUE TITLE
Call graphs list array literal type specification as function call

### ISSUE THREAD

**Issue by hornekyle** [cmacmackin/ford#82]
If an array literal defines its type it can be mistaken as a function call. Example:

[character(32)::'a','b']

**Comment by cmacmackin** [comment]
This bug was fixed as part of a previous bug report. These changes will 
be in the next release.

On 29/08/15 02:55 PM, Kyle Horne wrote:
>
> If an array literal defines its type it can be mistaken as a function 
> call. Example:
>
> [character(32)::'a','b']
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/82>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>
