### ISSUE TITLE
Graphviz required?

### ISSUE THREAD

**Issue by szaghi** [cmacmackin/ford#83]
Hi Chris,

Deplyoing FOODiE API doc by Travis CI I have found that Ford seems to require the graphviz module, it being not optional, e.g. see [this log](https://travis-ci.org/Fortran-FOSS-Programmers/FOODiE#L4013).

If graphviz is actually required and non optional, I think it is better to include graphviz as a required dependency [here](https://github.com/cmacmackin/ford/blob/master/setup.py#L49).

**Comment by cmacmackin** [comment]
Damn, I forgot to add it to the dependencies list. Thanks for pointing this out.

**Comment by cmacmackin** [comment]
Authored a new release with this as a dependency.

**Comment by szaghi** [comment]
Great Chris, thank you very much!
