### ISSUE TITLE
menu bar formatting?

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#84]
Hi Chris,
I'm not sure if this is an issue with my browser, or if we just need to rename the pages directory to be something a little bit shorter, but the [menu bar for JSON-Fortran](http://jacobwilliams.github.io/json-fortran) spills over onto two lines in my browser:

![screen shot 2015-09-01 at 9 41 41 am](https://cloud.githubusercontent.com/assets/279612/9605787/b30325be-508d-11e5-96dc-a6b170600a4d.png)

This is a relatively minor aesthetic issue, so if it's not worth fixing in your opinion, that's fine, we can work around it on our end. I just wanted to bring this to your attention and hear your thoughts on the matter.

**Comment by zbeekman** [comment]
Just to clarify this happens no matter how large my browser window is.

**Comment by cmacmackin** [comment]
This is an upstream issue with Bootstrap. They have a maximum width on 
the page that stuff is allowed to take up and displaying everything on 
one line would exceed it. For now the easy fix is, as you say, to rename 
the pages directory to something shorter. If you can suggest a logical 
way to group menu-items into a drop-down menu then I may do that in a 
future release.

On 01/09/15 10:45 AM, Izaak Beekman wrote:
>
> Just to clarify this happens no matter how large my browser window is.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/84#issuecomment-136727353>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by zbeekman** [comment]
OK, that's what I figured. I think, for now, it makes sense to just think of a better, shorter name for "Additional Documentation"
