### ISSUE TITLE
private type bound procedure and generic interface: strange behavior

### ISSUE THREAD

**Issue by szaghi** [cmacmackin/ford#9]
Hi Chris,

I used to define **private** the type-bound procedures constituting a type-bound generic **public** interface, e.g. into FLAP there is something like:
```fortran
type, public:: Type_Command_Line_Interface
  !< Derived type implementing a flexible Command Line Interface (CLI).
  integer(I4P)::                                  Na          = 0_I4P !< Number of CLA.
  ....
  contains
    procedure:: free
    ....
    generic::   get => get_cla_cli,get_cla_list_cli
    ! private procedures
    procedure,              private:: get_cla_cli
    procedure,              private:: get_cla_list_cli
endtype Type_Command_Line_Interface
```

As you can see here http://szaghi.github.io/FLAP/type/type_command_line_interface.html#bp-get_cla_list_cli it seems that Ford is trying to document also **get_cla_list_cli** (but not **get_cla_cli**), but the docstring of it is missing.

Is it a bug?

**Comment by cmacmackin** [comment]
Yes, this is. I am actually working on correcting it right now.
On 07/01/15 11:06 AM, Stefano Zaghi wrote:
>
> Hi Chris,
>
> I used to define *private* the type-bound procedures constituting a 
> type-bound generic *public* interface, e.g. into FLAP there is 
> something like:
>
> type,public::  Type_Command_Line_Interface
>    !< Derived type implementing a flexible Command Line Interface (CLI).
>    integer(I4P)::                                   Na=  0_I4P  !< Number of CLA.
>    ....
>    contains
>      procedure::  free
>      ....
>      generic::    get=> get_cla_cli,get_cla_list_cli
>      ! private procedures
>      procedure,private::  get_cla_cli
>      procedure,private::  get_cla_list_cli
> endtype Type_Command_Line_Interface
>
> As you can see here 
> http://szaghi.github.io/FLAP/type/type_command_line_interface.html#bp-get_cla_list_cli 
> it seems that Ford is trying to document also *get_cla_list_cli* (but 
> not *get_cla_cli*), but the docstring of it is missing.
>
> Is it a bug?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/9>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by cmacmackin** [comment]
Done. It will be uploaded in a minute or so.

**Comment by cmacmackin** [comment]
I've pushed this morning's bug-fixes. You can pull them down now.

**Comment by szaghi** [comment]
Works! And works also documenting all!

Great Chris!

Il giorno Wed Jan 07 2015 at 4:19:00 PM Chris MacMackin <
notifications@github.com> ha scritto:

**Comment by cmacmackin** [comment]
Glad to hear it! It's good to know that there will be people getting 
some use out of FORD.
On 07/01/15 11:26 AM, Stefano Zaghi wrote:
> Works! And works also documenting all!
>
> Great Chris!
>
> Il giorno Wed Jan 07 2015 at 4:19:00 PM Chris MacMackin <
> notifications@github.com> ha scritto:
>
> > I've pushed this morning's bug-fixes. You can pull them down now.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cmacmackin/ford/issues/9#issuecomment-69035796>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/9#issuecomment-69036972>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by szaghi** [comment]
Hi Chris,

Maybe I can help you to publish ford on PyPi. I have published some codes
on it. I think pybuilder being of great help. I you want help let me know.

See you soon.

Il giorno 03:26 gio 08/gen/2015 Izaak Beekman <notifications@github.com> ha
scritto:

**Comment by cmacmackin** [comment]
That would be very much appreciated! Thanks! I won't be doing that just 
yet, but maybe in a week or two.

On 08/01/15 01:11 AM, Stefano Zaghi wrote:
> Hi Chris,
>
> Maybe I can help you to publish ford on PyPi. I have published some codes
> on it. I think pybuilder being of great help. I you want help let me 
> know.
>
> See you soon.
>
> Il giorno 03:26 gio 08/gen/2015 Izaak Beekman 
> <notifications@github.com> ha
> scritto:
>
> > Thanks for the tips and the great work.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cmacmackin/ford/issues/9#issuecomment-69127174>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/9#issuecomment-69136833>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>
