### ISSUE TITLE
Handling of #include files

### ISSUE THREAD

**Issue by nncarlson** [cmacmackin/ford#90]
I'm having a problem with #include files.  If the included file is in the same directory as the source that includes it, there is no problem.  But if it is in a different directory, then the preprocessor can't find it resulting in an error like (--debug gives nothing additional):
> Warning: error preprocessing ./src/secure_hash/sha1_hash_type.F90
> ./src/secure_hash/sha1_hash_type.F90:46:0: fatal error: f90_assert.fpp: No such file or directory
>  #include "f90_assert.fpp"
>  ^
> compilation terminated.

Declaring the directory containing the include file with project_dir makes no difference.  It sounds like a "-I" option is needed for the preprocessing step.

**Comment by cmacmackin** [comment]
Thanks for the bug report. I'll fix this before the next release. However, I have just started grad school and am busy with that, so no promises on when the next release will be.

**Comment by cmacmackin** [comment]
My apologies for the delay in fixing this bug. I have now added an option in the project file called `include`. This consists of a list of directories to be searched for include files. These changes will be in the next release (hopefully later today) and the documentation in the wiki will be updated accordingly.

**Comment by nncarlson** [comment]
I'm a long time getting back around to trying this again, but it all looks good now.  Thanks!   Now to start tweaking my comments for FORD ...
