### ISSUE TITLE
Generic procedures within type

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#92]
[Here](http://jacobwilliams.github.io/json-fortran/type/json_file.html#boundprocedure-get) I've got a generic ```get``` procedure within the ```json_file``` type that is pointing to various routines (such as ```json_file_get_object```). However, the arguments aren't showing up for the individual routines, nor are the descriptions. Is there a way to make this happen? Currently they are [accidentally](https://github.com/cmacmackin/ford/issues/91) public, but when I make them private, the documentation won't show how to call them.

**Comment by cmacmackin** [comment]
This is definitely a bug. Off the top of my head I have no idea what 
could have caused it--I thought I had tested for this sort of situation. 
I'll have to look into it.

On 15-11-01 05:26 PM, Jacob Williams wrote:
>
> Here 
> <http://jacobwilliams.github.io/json-fortran/type/json_file.html#boundprocedure-get> 
> I've got a generic |get| procedure within the |json_file| type that is 
> pointing to various routines (such as |json_file_get_object|). 
> However, the arguments aren't showing up for the individual routines, 
> nor are the descriptions. Is there a way to make this happen? 
> Currently they are accidentally 
> <https://github.com/cmacmackin/ford/issues/91> public, but when I make 
> them private, the documentation won't show how to call them.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/92>.
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>

**Comment by cmacmackin** [comment]
Sorry for the delay in my fixing this. Turned out just to be a small, 
stupid little error in one of my comparison tests which made FORD try to 
output the wrong thing. The bugfix will be in a new release, hopefully 
later today.

On 15-11-01 08:17 PM, Chris MacMackin wrote:
> This is definitely a bug. Off the top of my head I have no idea what 
> could have caused it--I thought I had tested for this sort of 
> situation. I'll have to look into it.
>
> On 15-11-01 05:26 PM, Jacob Williams wrote:
>>
>> Here 
>> <http://jacobwilliams.github.io/json-fortran/type/json_file.html#boundprocedure-get> 
>> I've got a generic |get| procedure within the |json_file| type that 
>> is pointing to various routines (such as |json_file_get_object|). 
>> However, the arguments aren't showing up for the individual routines, 
>> nor are the descriptions. Is there a way to make this happen? 
>> Currently they are accidentally 
>> <https://github.com/cmacmackin/ford/issues/91> public, but when I 
>> make them private, the documentation won't show how to call them.
>>
>> —
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/cmacmackin/ford/issues/92>.
>>
>
> -- 
> Chris MacMackin
> cmacmackin.github.io <http://cmacmackin.github.io>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>
