### ISSUE TITLE
Public Homebrew install stats?

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#93]
I'm about to update the Homebrew formula for the latest release, and was wondering if you wanted me to ask the Homebrew folks to allow public access to FORD installation stats. [Here](https://bintray.com/homebrew/bottles/a2ps/view#statistics) are some for `a2ps`, for example. This data might  be useful when citing FORD or discussing it when applying for grant money. Just let me know and I can ask the Homebrew folks.

**Comment by cmacmackin** [comment]
Hi Izaak,
I am going to be putting out another release later today, so I suggest you wait before updating the Homebrew formula. Once I've gotten that out I'll reply to your question properly.

**Comment by cmacmackin** [comment]
I certainly have no qualm with getting access to FORD's installation stats. However, it's not something that I care enough about to want to put any extra work in myself. FORD is really just a hobby and I'm unlikely to ask for any grant money for it or to cite it in a paper. Frankly, the coding-style is too low quality for anything like that! So if it's just a matter of asking Homebrew to make this data public somewhere then go ahead, but if it requires either of us to put in any additional effort then I don't think it's worth it.

**Comment by zbeekman** [comment]
Yeah, all we need to do is ask... but I wanted to check with you first.

**Comment by zbeekman** [comment]
Download statistics have been made available here: https://bintray.com/homebrew/bottles/ford/view#statistics

This is an under-estimate due to the fact that people have to option to install the HEAD release which isn't bottled, and until my PR for the 4.4.0 formula is accepted, people on El Capitan are not able to install bottled FORD because no bottle has been created yet. (Bottles are created when formulae are tested which happens when a PR with changes is made...)

**Comment by cmacmackin** [comment]
Thanks!

On 15-11-28 05:22 PM, Izaak Beekman wrote:
>
> Download statistics have been made available here: 
> https://bintray.com/homebrew/bottles/ford/view#statistics
>
> This is an under-estimate due to the fact that people have to option 
> to install the HEAD release which isn't bottled, and until my PR for 
> the 4.4.0 formula is accepted, people on El Capitan are not able to 
> install bottled FORD because no bottle has been created yet. (Bottles 
> are created when formulae are tested which happens when a PR with 
> changes is made...)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/93#issuecomment-160321951>.
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>
