### ISSUE TITLE
exclude_dir ignored

### ISSUE THREAD

**Issue by perrette** [cmacmackin/ford#95]
I wish to build documentation for a project where some source files are in sub-directories, while others are in the current, root directory, under which the `doc` folder should also be placed. The simplest solution I figured for this case is was to have the root `./` as project_dir. I face the issue that when the doc needs to be rebuilt, it also search for files in `doc`, which it should not (double work !). Hence the use of the `exclude_dir: ./doc` option. Unfortunately, it does not seem to work, leaving and scan the `./doc` folder regardless...

Any hint? I use the pip version ford 4.4.0.

EDIT: use case, practically:
```
./
    - src1/
    - src2/
    - file1.f90
    - file2.f90
```

**Comment by perrette** [comment]
PS: `exclude` does not seem to work either...

**Comment by cmacmackin** [comment]
I've fixed this (along with some other issues surrounding exclude_dir) and should be authoring a new release sometime in the next few days.
