### ISSUE TITLE
Export graphs as images

### ISSUE THREAD

**Issue by zbeekman** [cmacmackin/ford#97]
Hi Chris,
Do you know if it's possible to export some of the automatically generated dependency/inheritance/call graphs as images from FORD?

**Comment by cmacmackin** [comment]
Ah. Before I added the zoom/pan feature (which seemed to require the SVG to be inline within the HTML) y

**Comment by cmacmackin** [comment]
And, by incredibly trivial, I mean that I can get graph files produced again by literally uncommenting [one line](https://github.com/cmacmackin/ford/blob/7898d0908928ada2660105c97e280527d12f7bb9/ford/output.py#L145)

**Comment by zbeekman** [comment]
haha great! Can I please put in a feature request that images get generated again? Another useful thing would be to output the graphviz dot source... But I'd settle for an SVG image. :-)

**Comment by cmacmackin** [comment]
The dot source will take marginally more work to do, but it shouldn't be a problem. No idea when the next release will be, though. If you want the SVG right away, then just uncomment the line I referenced in your own installation.

**Comment by zbeekman** [comment]
:+1:

**Comment by szaghi** [comment]
:+1:

**Comment by cmacmackin** [comment]
Added. Will be in the next release.

**Comment by zbeekman** [comment]
Epic, thanks so much!
